### ISSUE TITLE
pushbutton.py don't work

### ISSUE THREAD

**Issue by Enzoinventor** [shivasiddharth/GassistPi#103]
Hi, I noticed that the pushbutton.py command does not work
(env) pi@raspberrypi:~ $ python3 /home/pi/GassistPi/src/pushbutton.py
INFO:root:Connecting to embeddedassistant.googleapis.com
and then it remains locked there, 
the file gassistpi-push-button.service was compiled with my id data

**Comment by shivasiddharth** [comment]
As the title of the file says, its for trigger using a pushbutton connected between GPIO 22 and GRND. I have mentioned that in the introduction part of readme and also have mentioned it in the GPIO allocation table.

**Comment by Enzoinventor** [comment]
I apologize. I'm using the aiy kit and the button is connected to the 23 just enough that I edit the right file?

**Comment by Enzoinventor** [comment]
ok now it works but the stream news functions and all the others do not work like never?

**Comment by Sumeetgk** [comment]
my button is also not working how did u fixed it ?
