### ISSUE TITLE
How to stop the 'Mic's Back onhttps://github.com/shivasiddharth/GassistPi/issues/new/choose' and 'Mic is muted' announcement

### ISSUE THREAD

**Issue by Sudhesh78** [shivasiddharth/GassistPi#1060]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
ArmV7, Rev4, Hardware BCM2835, OS Raspbian Stretch

### Describe the bug: 
Is there a way we can stop the "Mics back on ' and 'Mic is muted' messages?

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues)?
Yes
### 2. Is the issue related to assistant installation ?
No

### 3. Does the assistant service start normally?
Yes/No  - it doesn't start automatically, but sometimes it starts. if Its not started and i run the startup Command, it will start twice. then i will kill the one i started from terminal, the other one will continue. 

### 4. Is the assistant service restarting automatically?
No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
The users are expected to stick to the issue template and fill it out diligently spending some time giving it a thought while filling in the details. It is not hard to run the given commands and fill in the Board and OS details. 

You say that you have gone through the issue, but clearly you have not. Just searching for "mic is back on" in the issues gives a list where this has been discussed. #948  #879
