### ISSUE TITLE
ImportError: No module named 'google.assistant.library' with raspberry pi zero w

### ISSUE THREAD

**Issue by idealist33** [shivasiddharth/GassistPi#107]
I am using raspberry pi zero w and executed "python main.py" then error comes out.

Already followed intruction of installation.

`(env) pi@raspberrypi:~/GassistPi/src $ python main.py`
`Traceback (most recent call last):
  File "main.py", line 26, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'
`

**Comment by shivasiddharth** [comment]
main.py is for Pi3 B and Pi2 B. For Pi Zero, its pushbutton.py

**Comment by shivasiddharth** [comment]
Since the clarification was given, closing this issue..
