### ISSUE TITLE
Say has along delay

### ISSUE THREAD

**Issue by Welsyntoffie** [shivasiddharth/GassistPi#1073]
I know what your going to say. "Not the place, post in Gitter"
There is no action there. I also know about [https://github.com/shivasiddharth/GassistPi/issues/629](url) ,but that was never solved.

Any way. I have the same issue while using domoticz commands. Voice takes between 10 and 40 seconds while the assistant just hangs there. After that the assistant translates and execute the given command. Which is why I swaped the order of the command and the say.
Using it this way switches my LED or brightness in less than 1 second then I just sit back and wait for voice before geving next command.

I have replaced all https with http in the domoticz section and changed the port in the config, thinking that bypassing ssl would soeed it up. That just crashes and the assistant restarts. So I changed back to https.
I even tried to shorten the say speech to just OK. To make it faster, but that also does not work.

I did have pulseaudio installed, so I uninstalled it and fresh install alsa so that all audio is default.
That majorly improved the google speech and the sound after the wake word. Response for what is the time is double as fast with alsa compared to pulseaudio.

I did not use template because all terminals are the same as in [https://github.com/shivasiddharth/GassistPi/issues/1071](url)
It hangs before say or in the proccess of translating.

Oppologies for posting here and not in gitter. I've spent the last 18hours trying to figure it out.

**Comment by shivasiddharth** [comment]
I dont understand as to what do you mean by "there is no action there ?" I go through all the comments there and provide help. You have sent a personal message couple of hours back. You need to understand that developers are human who are not always online 24x7 and who may be in a different time zone than you.

First, you need to understand as to how the text to speech works.

Its is not happening locally on the Pi to shorten the delay. It happens over the internet. The text is uploaded to internet and speech is generated and then downloaded. The downloaded audio is then played using a program on the Pi. All these things are being done without any premium APIs or programs and it will take time and is not going to happen instantaneously. Other factors that the delay depends on are the processing capability of Pi and the network speed. Same program on a Pi4 may not take as much time as on Pi3.

If you want something faster, you need to shorten the text thats the only way. Change all the say commands to say ("Ok").
