### ISSUE TITLE
Wakeword doesn't seem to work after reboot

### ISSUE THREAD

**Issue by seremana** [shivasiddharth/GassistPi#110]
Hello,

First of all, thank you for this nice consolidation of google assistant PI tools.
Installation went successfull, however, the wakeword doesn't seem to work after PI reboot.  I hear the welcome sound after restart.

The assistent works smooth after manual start (python -u /home/pi/GassistPi/src/main.py --project_id 'xyz'  --device_model_id 'xyz-n')

Any idea what can be going on?

Thank you!

**Comment by shivasiddharth** [comment]
Did you set the model id and project id in the systemd file ? Please see point:1 under [headless-autostart-on-boot-service-setup](https://github.com/shivasiddharth/GassistPi#headless-autostart-on-boot-service-setup)

**Comment by seremana** [comment]
I did, and it does work after trying some time. Just not that good, it appears to have difficulties understanding me.  Could be my mic, could be software related.  I'll look into it.  Thanks!

**Comment by shivasiddharth** [comment]
Since the issue seems to be resolved, closing this issue !
