### ISSUE TITLE
Error 400 with OAuth2

### ISSUE THREAD

**Issue by seb29470** [shivasiddharth/GassistPi#112]
Hi,

when I Copy the google assistant authentication link from terminal and authorize using your google account, I have an Error 400:
Error: redirect_uri_mismatch

Is it because I use an Web credential?

Thanks to your advice

**Comment by shivasiddharth** [comment]
You chose "web application" while creating credential ? You should choose "other"!

**Comment by seb29470** [comment]
Thank you, it works
