### ISSUE TITLE
Google's gone?!

### ISSUE THREAD

**Issue by mikecheng2626** [shivasiddharth/GassistPi#1132]
Followed the instructions
1st attempt: was able to talk to Google

went to src/config.yaml --> enabled custom wakeword to snowboy, disabled OK_Google wakeword.
Tried talking to Google or snowboy again --> no response

Changed back enabled OK_Google and disabled snowboy
Tried talking to Google again --> no response

What should I do?

**Comment by shivasiddharth** [comment]
Please open an an issue for only a real issue with the program. For other help and queries use gitter.
