### ISSUE TITLE
Snowboy Wakeword Detection

### ISSUE THREAD

**Issue by Sk3yNet** [shivasiddharth/GassistPi#1134]
### Which branch of GassistPi are you using ?
Main

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo:
> processor       : 0
> model name      : ARMv7 Processor rev 3 (v7l)
> BogoMIPS        : 108.00
> Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant     : 0x0
> CPU part        : 0xd08
> CPU revision    : 3
> 
> Hardware        : BCM2711
> Revision        : b03114
> Serial          : 10000000d0c5c130
> Model           : Raspberry Pi 4 Model B Rev 1.4 

cat /etc/os-release 
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

cat /etc/rpi-issue

> Raspberry Pi reference 2021-03-04
> Generated` using pi-gen, https://github.com/RPi-Distro/pi-gen, 461109415073d2eb67083709662ba983cc191f14, stage4

### Describe the bug:
```
Assistant functions with Google wakewords but not with Snowboy wakewords (custom or example). I found that Snowboy custom wakeword creation is possible with [https://github.com/rhasspy/snowboy-seasalt](https://github.com/rhasspy/snowboy-seasalt). Being that Picovoice charges for custom wakewords on RPi, Snowboy is preferred. Would it be possible to fix the [bugs](https://github.com/shivasiddharth/GassistPi/issues/1133#issuecomment-833318311) in existing code to re-enable the service?
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues)?
Yes

### 2. Is the issue related to assistant installation ?
No

### 3. Does the assistant service start normally?
Yes, with error

### 4. Is the assistant service restarting automatically?
No

### If answer to question 4 is No, then proceed further.
### Manually start the assistant. For guidelines to start the assistant manually refer [this](https://github.com/shivasiddharth/GassistPi#manually-start-the-assistant)

### Paste the command below, that crashed the assistant
```
/home/pi/env/bin/python -u /home/pi/GassistPi/src/pushbutton.py --project-id 'ID' --device-model-id 'Dev ID'
```

### Paste the contents of the terminal below
```
Respeaker-2-Mic
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/pushbutton.py", line 1034, in <module>
    main()
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/GassistPi/src/pushbutton.py", line 945, in main
    callbacks = [detected]*len(models)
NameError: name 'models' is not defined
```

**Comment by shivasiddharth** [comment]
Snowboy has compatibility issues. It is raising ctypes errors when used with some of the other python packages. I wasted 4 days trying to fix that. I don't think it is wise to invest anymore time on a deprecated module. I have already had this discussion in the gitter. If you do not want any of the features of the master branch, use the custom wakeword branch. Snowboy will work there. 
I am finding alternatives to Picovoice. Cheap - Best - Fast never come together. It's always a compromise.
