### ISSUE TITLE
unable to use gpio triggering

### ISSUE THREAD

**Issue by amanmathurastro** [shivasiddharth/GassistPi#114]
i have install modified version of google assistant sdk but not able to use the gpio pins using hey google its not responding .......??? help me out as soon as possible .. i m using raspi 3

**Comment by shivasiddharth** [comment]
Did you add the project-id and model-id ? Only if you can share the error, i can comment on that.

**Comment by amanmathurastro** [comment]
yes i did that ..... actually it is responding in every query but when i say to on the kitchen lights or trigger servo 90 it didn't respond. It also not responding to any gpio related query.

**Comment by shivasiddharth** [comment]
It may not be decoding your query properly. stop the assistant using:  
`sudo systemctl stop gassistpi-ok-google.service`
Start the main.py manually using:
` /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --project_id 'project-id'  --device_model_id 'saved-model-id'`
Now give your command and see whether its detecting your command.

**Comment by amanmathurastro** [comment]
thank you sir.... just last quetion than i"ll close the issue instead of this can i use node mcu one to serve my purpose?

**Comment by amanmathurastro** [comment]
thank you sir .... i am closing this issue
