### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by coconuthero** [shivasiddharth/GassistPi#120]
Hi Sid,

how can I change the language of the google assistant to german?

Thanks!

**Comment by shivasiddharth** [comment]
Open the assistant app on phone/tablet, select more settings, choose your device and change the language.

**Comment by coconuthero** [comment]
I checked the assistant app on my Sony Xperia Z5 with Android 7.1.1 thorougly but the raspberry pi is not listed although the assistant is active on the pi. I also checked the google home app without succsess...

**Comment by shivasiddharth** [comment]
i have shown here as to how you can access the settings https://youtu.be/vprJBDDYE8Q?t=999

**Comment by coconuthero** [comment]
This seems to be disabled in Switzerland

**Comment by BadFlo** [comment]
Same here, cannot see the GAssist RasPi on Google Home app ... in Switzerland.
