### ISSUE TITLE
Autostart Assistant

### ISSUE THREAD

**Issue by coconuthero** [shivasiddharth/GassistPi#121]
Hi Sid,
I want to make a magic mirror. How can I automatically start google assistant after booting?
Thank you!

**Comment by shivasiddharth** [comment]
I have clearly given that in the README https://github.com/shivasiddharth/GassistPi/blob/master/README.md#headless-autostart-on-boot-service-setup

**Comment by coconuthero** [comment]
I apologize for my question but doesn't headless Autostart mean, that the
screen will be switched off? (I need the screen for my project) Sorry if I
understand it wrong!

Am 06.01.2018 01:34 schrieb "shivasiddharth" <notifications@github.com>:

I have clearly given that in the README https://github.com/
shivasiddharth/GassistPi/blob/master/README.md#headless-
autostart-on-boot-service-setup

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shivasiddharth/GassistPi/issues/121#issuecomment-355703967>,
or mute the thread

**Comment by shivasiddharth** [comment]
Headless does not mean that display will not work. Headless means that your code will auto start on boot and run in the background.

**Comment by coconuthero** [comment]
That's good news! I googled headless and according to the definition I
found it means that a system is running without graphical interface.

Am 10.01.2018 10:24 schrieb "shivasiddharth" <notifications@github.com>:

Headless does not mean that display will not work. Headless means that your
code will auto start on boot and run in the background.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shivasiddharth/GassistPi/issues/121#issuecomment-356546754>,
or mute the thread
