### ISSUE TITLE
saving credentials in wrong directory

### ISSUE THREAD

**Issue by tityann** [shivasiddharth/GassistPi#124]
hello sorry for bad english , i am french
 after enterring the autorisation code, the credentials.json file is saved
in your video example , it is saved in home/pi but for me your script saved it into:

Enter the authorization code: XXXXX.........
**credentials saved: /root/.config/google-oauthlib-tool/credentials.json**
Creating new device model
.....

into the root directory
I have no modified the script and i start the script with your command

**Comment by shivasiddharth** [comment]
This is an issue with Raspbian OS. This has already been discussed here: #88

**Comment by tityann** [comment]
tanks
