### ISSUE TITLE
Raspberry PI Zero W Gassistant Problam

### ISSUE THREAD

**Issue by kumarmohan7** [shivasiddharth/GassistPi#125]
Hi,

In My Raspberry Pi Zero W Gassistant Installation Problem,
In final Execution Stage this Error is Coming

Please give solution for solve problem....

INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: '/home/pi/.config/googlesamples-assistant/device_config.json'
INFO:root:Registering device
ERROR:root:Failed to register device: {
  "error": {
    "code": 400,
    "message": "Could not create the device instance. Client type need to be specified as SDK_LIBRARY or SDK_SERVICE.",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by shivasiddharth** [comment]
If you already have a device registered and showing in the app, unlist/remove that device in the app and try registering the pi zero again.

**Comment by kumarmohan7** [comment]
Hi,
Thank u for replay,
How to remove the device & more then one device enable any problem is coming  or any limitation is available...?

**Comment by shivasiddharth** [comment]
I have already demonstrated the unlinking process in the youtube video :https://youtu.be/vprJBDDYE8Q

**Comment by shivasiddharth** [comment]
Closing this issue !
