### ISSUE TITLE
Google assistant slow response

### ISSUE THREAD

**Issue by tstasevych** [shivasiddharth/GassistPi#129]
Great project! Keep it going! 

One issue that i am facing however that after asking a question, it takes 10-15 seconds for response. Google Assistant on phone, or on Google Home works times faster. What is the reason behind it?

Thank you!

**Comment by shivasiddharth** [comment]
It could be due to several reasons.
1. Lower processing power of Pi, when compared to other devices.
2. The multiple conditional statements that we have introduced for custom actions.
3. Network issues.

**Comment by tstasevych** [comment]
How can I disable some of the conditional statements to test if that is the issue?

**Comment by shivasiddharth** [comment]
Feel free to try whatever you feel like trying. Even if the script gets messed, anytime, you can get the script again from the git

**Comment by shivasiddharth** [comment]
As i have not heard back, I am assuming that the issue has been resolved and closing this for now !
