### ISSUE TITLE
suggested minor Arduino fixes

### ISSUE THREAD

**Issue by mickeypop** [shivasiddharth/GassistPi#132]
1)
lines 42 and 43, not all micros are the same this fixes most  ATMEGA, ESP8266 and ESP32 
    pinMode(BUTTON_PIN1, INPUT);
        change to 
    pinMode(BUTTON_PIN1, INPUT_PULLUP);
after 1.6.2 IDE, INPUT_PULLUP turns on the internal pullup of the micro

2)
this fixes any change in "numPixels" regardless of the micro
Line 156   address  changing number of pixels
     if ( startValue == 12 )
        change to
      if ( startValue == numPixels )

**Comment by shivasiddharth** [comment]
Thanks for the shout. Have incorporated the suggestions.
