### ISSUE TITLE
Voice return is quiet

### ISSUE THREAD

**Issue by tjzggc** [shivasiddharth/GassistPi#133]
After getting the code working for the second time, the first since the newest update everything works well until the assistant responds to the question. The beep is loud like watching a video on the internet, but when the assistant answers the answer is much quieter than anything else. Is there an option for making this part of the voice control loud like the speaker does for everything else?

**Comment by shivasiddharth** [comment]
Please see point-6 under : https://github.com/shivasiddharth/GassistPi#continue-after-setting-up-audio

The same has also been mentioned in https://github.com/googlesamples/assistant-sdk-python/issues/145
