### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by wanleg** [shivasiddharth/GassistPi#14]
Just a quick one: in Step 4.2, /home/pi/GassistPi/scripts/snowboy-deps-installer.sh requires pip, which isn't installed if you run that one first, before /home/pi/GassistPi/scripts/gassist-installer-pi-zero.sh

Might want to tweak that for absolute newbies following your otherwise superb guide.

**Comment by shivasiddharth** [comment]
Newer versions of Raspbian come installed with pip. But have added that now anyways. Thanks for pointing it out.
