### ISSUE TITLE
Multiple ESP handling (Done)

### ISSUE THREAD

**Issue by VinceW31** [shivasiddharth/GassistPi#141]
I've changed my instance of Main.py and Actions.py to now handle multiple ESPs/SonOff wireless switches.  I currently have 4 separate ESP/SonOff switches, each one controlling a single device (standard lamp, dishwasher, washing machine, charger, etc) this is much simpler than having 1 ESP controlling 3 or 4 devices with different GPIOs,  So now, instead of using the trigger word "wireless", I use "lamp", "dishwasher" etc. followed by "On" or "Off".

I've updated my files for controlling the first of my ESP/SonOff switches (which controls my Standard Lamp) as shown below; for additional ESP/SonOff switches follow the same procedure again and create new/additional "def" steps with your chosen trigger names:

**In Actions.py** 
**replace:**
_#IP Address of ESP
IP='xxxxxxxxx'_
**with:**
_#IP Address of ESPs/SonOff
ESP1_url='192.168.1.95/control?cmd=event,' # Lamp 
ESP2_url='192.168.1.xxx/control?cmd=event,' # replace xxx with your specific ESP ip address details
ESP3_url='192.168.1.xxx/control?cmd=event,' # replace xxx with your specific ESP ip address details
ESP4_url='192.168.1.xxx/control?cmd=event,' # replace xxx with your specific ESP ip address details_
**Insert new lines in Actions.py, after the #ESP8266 Devcies control def block, as follows:**
_#Standard Lamp control_
_def Lamp(phrase):
if` 'on' in phrase:
        event='TurnOn'
        #say("Turning lamp on ")
        subprocess.Popen(["elinks", ESP1_url + event],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
        time.sleep(2)
        subprocess.Popen(["/usr/bin/pkill","elinks"],stdin=subprocess.PIPE)
    elif 'off' in phrase:
        event='TurnOff'
        #say("Turning lamp off ")
        subprocess.Popen(["elinks", ESP1_url + event],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
        time.sleep(2)
        subprocess.Popen(["/usr/bin/pkill","elinks"],stdin=subprocess.PIPE)
    else:
        say("sorry, I didn't get that")_

I've also deleted everything within "Declaration of ESP names" as its not needed any more.

**In Main.py**
**At the top of the file after**
_from actions import ESP_
**insert:**
_from actions import Lamp_
**after the block:**
            _if 'wireless'.lower() in str(usrcmd).lower():
                assistant.stop_conversation()
                ESP(str(usrcmd).lower())_
**insert new block:**
            _if 'lamp'.lower() in str(usrcmd).lower():
                assistant.stop_conversation()
                Lamp(str(usrcmd).lower())_

All seems to work fine so far.

**Comment by shivasiddharth** [comment]
Can you fork, make these modifications and generate a pull request, will add it to the git. Thanks
