### ISSUE TITLE
Radio "Tune into" trigger

### ISSUE THREAD

**Issue by VinceW31** [shivasiddharth/GassistPi#142]
The current Radio "Tune into" trigger gets interpreted as "Tune in to" and therefore will not always work.  Ive just added another second trigger event into Main.py after the current "Tune into" block as follows :
            if 'tune in to'.lower() in str(usrcmd).lower():
                assistant.stop_conversation()
                radio(str(usrcmd).lower())

**Comment by shivasiddharth** [comment]
Yup ! Those trigger words are not general and as the pronunciation differs from person to person, we tend to get varied results. Instead of adding a sub-block, you can infact change the "tune into" to "tune in to" or something else.
