### ISSUE TITLE
Streaming Radio problem after update 09/01/18

### ISSUE THREAD

**Issue by ifb777** [shivasiddharth/GassistPi#148]
So the time has come again to seek advice from this list.
Having got most features working reasonably reliably over the past couple of weeks, I decided to update GassistPi to the 9th January version.
Since then, issuing the command "hey google,  Tune into, Radio One",  now just responds with...."Sorry, I don't know how to help with that".  The same result for successive stations.
Prior to the update, Streaming Radio using the default stations and some additional stations that I added worked well.
I have reviewed the code for this function in actions.py and can see no differences between the working version of the code and the updated version and as a non coder, I am now at a loss as to where to go from here.
Any thoughts or suggestions would be very welcome as this is a game changer for the project I'm working on.

My thanks in advance.

**Comment by shivasiddharth** [comment]
Hope this #142 gives you some idea.

**Comment by ifb777** [comment]
Yet again I must thank you for the prompt response to this issue.

I have had a play around with the words and found that "Tune in to" produces results albeit not as reliably as I would like.  I'm hoping a little more training in vocalising the command may improve the situation.  There is no doubt that "Tune into" worked well prior to the upgrade but I guess that's another story.
Thanks again for the input.  I'll leave this thread open for a while and play some more.
