### ISSUE TITLE
Why a "snowboy service starting" prompt every time pi starts?

### ISSUE THREAD

**Issue by AkterAhsan** [shivasiddharth/GassistPi#15]
I have done all of your instruction. but when I turn on my pi google assistant is ok but sonwboy not working. it's always say's "Starting snowboy service". What can i do. i'm using onboard jack and usb mic.

**Comment by shivasiddharth** [comment]
I have set the services to restart if it ran into some error. Did you make any changes to the snowboy.py file ?

**Comment by AkterAhsan** [comment]
Nope..

**Comment by AkterAhsan** [comment]
Does your ISO file work?

**Comment by shivasiddharth** [comment]
I have merged all the projects into one. So old procedures are no longer valid. Did you implement this from scratch by preparing a clean OS ? If you are implementing this over a pre existing assistant it will not work. Snowboy works only with python2.

**Comment by AkterAhsan** [comment]
I start with a clean OS

**Comment by shivasiddharth** [comment]
run the following command in the terminal and paste the output here.

sudo systemctl status snowboy.service

**Comment by shivasiddharth** [comment]
ok, i get your point now. The custom wakeword service has been bundled with Snowboy. So starting snowboy sevice means that the custom wakeword detection is starting. Its not an error.
