### ISSUE TITLE
Consider using Python wheels instead of compiling RPi.GPIO for performances

### ISSUE THREAD

**Issue by paolorotolo** [shivasiddharth/GassistPi#150]
Please read here how to use wheels to install Python packages on ARMv7 platforms quicker: https://forums.resin.io/t/precompiled-python-wheels-for-arm/591

Actually RPi.GPIO installation took almost 30 minutes on my Pi3.

**Comment by shivasiddharth** [comment]
Was actually planning to do all the housekeeping in the next update. lxml installation does take a ton of time as well.

**Comment by paolorotolo** [comment]
That's cool! Let me know if you need a hand.

**Comment by paolorotolo** [comment]
Nice one
