### ISSUE TITLE
After restarting the Pi 3 the startup sound of Gassistpi is continuously repeating 

### ISSUE THREAD

**Issue by Sumeetgk** [shivasiddharth/GassistPi#153]
After installing the New Gassistpi the startup sound is continiously repeating even if i stop the service any fix

**Comment by shivasiddharth** [comment]
There is no way the service will keep running even after you have stopped it. Please make sure to stop the correct service. The systemd file may not have been edited with the project-id and model-id, that could be the reason for the service restarts.

**Comment by shivasiddharth** [comment]
I am assuming that this has been resolved as you have moved on !
