### ISSUE TITLE
PushButton doesn't work in GPIO22 

### ISSUE THREAD

**Issue by Sumeetgk** [shivasiddharth/GassistPi#158]
I followed your video and in the readme file u told that ok google service and push button have a different way of - and _ so don't copy paste I have done everything as u said ! then I have connected the button in gpio 22 on my pi3 and when I click it doesn't responds! but if I say hey google it gets triggered but not via a button 

else everything is working as u said just have the issue in button plz help me with it! 
thnx

**Comment by shobha13** [comment]
i have the same problem do u know how to fix this???
