### ISSUE TITLE
YouTube Streaming command does not work. Restarts the Assistant Service

### ISSUE THREAD

**Issue by Sumeetgk** [shivasiddharth/GassistPi#163]
Youtube playback is not working i have shown the issue in this video
plz take a look at it if something went wrong correct me 

https://youtu.be/NRXVYSH7PO4

waiting for ur reply

**Comment by shivasiddharth** [comment]
1. Is this issue with Voice activated assistant and pushbutton or only one?
2. Did you check the media volume?
3. Right click on the Pi directory, choose "Show Hidden" and open a file called .mediavolume.json and see the current volume.
4. Log files are deleted on every restart/shutdown, otherwise, you should have the Log File.

**Comment by Sumeetgk** [comment]
1)This issue is occurring in both of the cases (pushbutton as well as voice) 
2)Yes the media volume is maximum but the service gets restarted so i dont think media volume is the issue 
3)There is no file in the default pi location called mediavolume.json
![screenshot 42](https://user-images.githubusercontent.com/10483810/35484062-4d670e34-0470-11e8-9d5c-7527629f31a7.png)

4) as i shown in the video i havent restarted the pie...i shown it just after the issue and there is no log 
   
waiting for ur reply

**Comment by shivasiddharth** [comment]
Stop the service and manually run the main.py. You will definitely see a log then.  When it crashes check the log file and upload it here.

**Comment by Sumeetgk** [comment]
Ok uploading the screenshot there is still no log file in tmp also available in screenshot 
![screenshot 44](https://user-images.githubusercontent.com/10483810/35484437-c31b2c50-0475-11e8-8bed-28ca7bb7a63e.png)

**Comment by shivasiddharth** [comment]
Nope, this not how main.py should be manually run. Open the systemd file that you modified, copy the line that says `ExecStart=` paste it in the terminal and execute.

**Comment by Sumeetgk** [comment]
bro, I'm not that pro in all of this like u but I have managed to run the file u said 

pi@raspberrypi:~/GassistPi/src $ ExecStart=/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py  --project_id vernal-sunspot-160703  --device_model_id vernal-sunspot-160703-20180128085643
bash: -u: command not found

attaching screenshot for better reference 

![screenshot 45](https://user-images.githubusercontent.com/10483810/35484582-db7ff9fe-0477-11e8-9fb8-f810b705cb1c.png)

**Comment by shivasiddharth** [comment]
You should not include the ' ExecStart='. Just execute whatever is there after the = symbol.

**Comment by Sumeetgk** [comment]
pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py  --project_id vernal-sunspot-160703  --device_model_id vernal-sunspot-160703-20180128085643

WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 11.0.0
INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:gmusicapi.Mobileclient1:authenticated
DEBUG:gmusicapi.Mobileclient1:Config(args=[], kwargs={})
DEBUG:gmusicapi.Mobileclient1:{'data': {'entries': [{'value': 'false', 'kind': 'sj#configEntry', 'key': 'canManageFP'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'shouldShowLocalSuggestions'}, {'value': '3', 'kind': 'sj#configEntry', 'key': 'purchaseAccess'}, {'value': '30000', 'kind': 'sj#configEntry', 'key': 'wsVdtMillis'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'sideloadedPlaybackLogging'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isWarmWelcomeDisabledForWoodstock'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'canCancelSubscription'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'nashvillebg'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isVsAvailable'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'canBrowseSt'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'appstoreRatingPrompt'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellDrawerCtaMessage'}, {'value': "Download and listen to any song, album, or station when you're not connected", 'kind': 'sj#configEntry', 'key': 'upsellDrawerDownloadMessage'}, {'value': '5000', 'kind': 'sj#configEntry', 'key': 'wsVatMillis'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'nuqRequiredForWsSignup'}, {'value': 'GET MORE', 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitTwoLeftCtaMessage'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellNewReleasesCtaMessage'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellListenNowCtaMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableWsExtras'}, {'value': 'Subscribe to get millions of songs on-demand, offline, and ad-free', 'kind': 'sj#configEntry', 'key': 'upsellSignedOutMessage'}, {'value': '500', 'kind': 'sj#configEntry', 'key': 'topListMaxSize'}, {'value': '2 skips left', 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitTwoLeftMessage'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'showLMark'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'conciergeListenNow'}, {'value': '6', 'kind': 'sj#configEntry', 'key': 'minimumAppStartCountForFreeUpsell'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellPreviousCtaMessage'}, {'value': "Download and listen to any song, album, or station when you're not connected", 'kind': 'sj#configEntry', 'key': 'upsellDownloadMessage'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'showYoutubeRedInfoCard'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'concListenNow'}, {'value': '300', 'kind': 'sj#configEntry', 'key': 'instantSearchDelay'}, {'value': 'Subscribe to play any song or album', 'kind': 'sj#configEntry', 'key': 'upsellChartsMessage'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isPodcastSyncEnabled'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellChartsCtaMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'showViOSL'}, {'value': '604800', 'kind': 'sj#configEntry', 'key': 'topListUpdatePeriodSeconds'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isSuggestDeletionEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'shouldShowServerSuggestions'}, {'value': '30', 'kind': 'sj#configEntry', 'key': 'situationsResponseTTLMinutes'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isFoplessNautilusUser'}, {'value': '1459804296734', 'kind': 'sj#configEntry', 'key': 'appStartCountForFreeUpsellRevisionNumber'}, {'value': 'Choose your language preference here, too.', 'kind': 'sj#configEntry', 'key': 'mgRPBDesc'}, {'value': '1', 'kind': 'sj#configEntry', 'key': 'partridgeManagement'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'showB'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'showA'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'shouldEnableThriller'}, {'value': 'Subscribe to play any song or album', 'kind': 'sj#configEntry', 'key': 'upsellThumbsUpMessage'}, {'value': '100', 'kind': 'sj#configEntry', 'key': 'topListPageSize'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isHallmarkEnabled'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellThumbsUpCtaMessage'}, {'value': '3', 'kind': 'sj#configEntry', 'key': 'uploadAccess'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isNautilusAvailable'}, {'value': '2', 'kind': 'sj#configEntry', 'key': 'nautilusAccess'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isQuizEnabledForWoodstockOnSignup'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'showO'}, {'value': '200000', 'kind': 'sj#configEntry', 'key': 'disabledConnectivityTimeoutMs'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'hasPControlSettings'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'wasRecentlyInFoplessNautilus'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'showV'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellSignedOutCtaMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'forceSignupFlow'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isNautilusUser'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isLNEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'wasEverInNautilus'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'ytContent'}, {'value': 'GET MORE', 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitOneLeftCtaMessage'}, {'value': '5000', 'kind': 'sj#configEntry', 'key': 'wsAatMillis'}, {'value': '1', 'kind': 'sj#configEntry', 'key': 'partridgeAccess'}, {'value': 'LISTEN_NOW', 'kind': 'sj#configEntry', 'key': 'warmWelcomeButtonText'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellPrerollVideoCtaMessage'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isTrAvailable'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isInAppMessageEnabled'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'disableInfoCardsOnDayOne'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'canRC'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'searchClusterResponseEnabled'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitCtaMessage'}, {'value': 'Google Play Music Free', 'kind': 'sj#configEntry', 'key': 'accountType'}, {'value': 'Subscribe for all of the music on-demand and offline with none of the ads', 'kind': 'sj#configEntry', 'key': 'upsellPrerollVideoMessage'}, {'value': 'Subscribe to get millions of songs on-demand, offline, and ad-free', 'kind': 'sj#configEntry', 'key': 'upsellListenNowMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isSuggestRequestEnabled'}, {'value': '12600325,12600335,12600357,12600365,12600387,12600390,12600394,12600397,12600426,12600428,12600430,12600443,12600465,12600466,12600467,12600506,12600526,12600530,12600536,12602070,12611729,12616614,12616615,12617467,12619033,12619127,12620830,12624217,12625361,12625500,12625941,12626008,12626945,12627951,12628012,12628654,12629142,12629667,12630065,12630209,12631091,12631414,12631643,12632064,12633320,12634000,12636020,12638179,12641836,12641837,12642011,12642809,12643537,12649046,20350003', 'kind': 'sj#configEntry', 'key': 'experimentIdsToLog'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isExplicitRestrictedByPControl'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isAnyServiceAvailable'}, {'value': 'NO_EXPERIMENT', 'kind': 'sj#configEntry', 'key': 'pieDayOneCard'}, {'value': 'Replay that song and millions of others, anytime', 'kind': 'sj#configEntry', 'key': 'upsellPreviousMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isAcceptedUser'}, {'value': '250', 'kind': 'sj#configEntry', 'key': 'appStartCountForFreeUpsell'}, {'value': '3', 'kind': 'sj#configEntry', 'key': 'wsAccess'}, {'value': '{\n  "userTenureIntervalWindow": {\n    "startMillis": "15552000000",\n    "endMillis": "622080000000"\n  },\n  "adsSessionConfig": [{\n    "sessionIntervalWindow": {\n      "startMillis": "0",\n      "endMillis": "3600000"\n    },\n    "firstAdOffsetMillis": "549000",\n    "timeBetweenAdsMillis": "720000"\n  }, {\n    "sessionIntervalWindow": {\n      "startMillis": "3600000",\n      "endMillis": "2592000000"\n    },\n    "firstAdOffsetMillis": "549000",\n    "timeBetweenAdsMillis": "720000"\n  }]\n}', 'kind': 'sj#configEntry', 'key': 'fcapConfigJson'}, {'value': '10', 'kind': 'sj#configEntry', 'key': 'androidTvEntityPageSize'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isPlSharingEnabled'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'showLNInSettings'}, {'value': 'Improve your recommendations', 'kind': 'sj#configEntry', 'key': 'mgRPB'}, {'value': '1', 'kind': 'sj#configEntry', 'key': 'ytSubscriptionAccess'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellDrawerDownloadCtaMessage'}, {'value': '1 skip left', 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitOneLeftMessage'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isDeviceVersionBlacklisted'}, {'value': '1800000', 'kind': 'sj#configEntry', 'key': 'wsPrefetchedAaeMillis'}, {'value': '300407000', 'kind': 'sj#configEntry', 'key': 'minimumGsaVersionRequiredForSoundSearch'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isSoundSearchEnabled'}, {'value': '150', 'kind': 'sj#configEntry', 'key': 'suggestRequestDelayMillis'}, {'value': "You're out of skips. Get on-demand and offline access to millions of songs.", 'kind': 'sj#configEntry', 'key': 'upsellSkipLimitMessage'}, {'value': 'SUBSCRIBE', 'kind': 'sj#configEntry', 'key': 'upsellDownloadCtaMessage'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isInstantSearchEnabled'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'hasNewUserQuizPermission'}, {'value': 'Subscribe to play any song or album', 'kind': 'sj#configEntry', 'key': 'upsellNewReleasesMessage'}, {'value': '100001', 'kind': 'sj#configEntry', 'key': 'persistentSubscriptionTrackUserLimit'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'shouldValidateMediaRoutes'}, {'value': '[{"packages": ["com.google.android.music", "com.google.android.setupwarlock", "com.google.android.gms"], "sha1s": ["38918A453D07199354F8B19AF05EC6562CED5788", "58E1C4133F7441EC3D2C270270A14802DA47BA0E"]}, {"packages": ["com.sonos.acr"], "sha1s": ["7387C9EB17CC5972F2B2FDF3E192884A78F24E7E", "62E2D848EF6FD0F8978F650D5DF9605786E26673", "9407A78494B106461537E1FC4E5D877E5ABCC7B3", "B6EA208733731F0CA8A123155830457C876130C4", "B703697E509B186616D83E978064A7A4F8D18775"]}]', 'kind': 'sj#configEntry', 'key': 'mediaRoutePackageSignatures'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableFallbackForShortUrls'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosEnableStreamInterception'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableStructuredLogging'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableHttpsAlbumArt'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isUpgradeTempCacheForKeeponEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableCQ'}, {'value': '2872939A', 'kind': 'sj#configEntry', 'key': 'castReceiverAppId'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosHashCastAppContext'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableWoodstockCloudQueue'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableBackgroundDownloading'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableRadioDownloads'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosRadioDownloadsAlwaysUseDownloadedSongs'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosRadioDownloadsEagerRefill'}, {'value': '25', 'kind': 'sj#configEntry', 'key': 'iosRadioDownloadsBatchSize'}, {'value': '80', 'kind': 'sj#configEntry', 'key': 'iosRadioDownloadsReadyPercent'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosEnableGPMAudioPlayer'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosEnableGPMAudioPlayerFMP4'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableAndroidChromecastCloudQueue'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableAndroidChromecastCloudQueueWoodstock'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableAndroidDialCloudQueue'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosEnableSonos'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'enableMpsOverride'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableReportAllPlayEventsInRealtime'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'askForNautilusCancellationReason'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'autoDogfoodStackCandidate'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'enableDGEvaluation'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableAdaptiveHome'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'iosEnableAdaptiveHome'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableOkHttp'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isSyncLoggingEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'enableOnePushSync'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableOnepushNew'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableGcmRegistrationNew'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'androidEnableEntitySuggest'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableEntitySuggest'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'musicFeedbackLogs'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isPrimesOdysseyEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isPrimesClearcutEnabled'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'isPrimesMemoryEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'iosEnableStickyNav'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'androidEnableStickyNav'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableAdaptiveHomeForMediaBrowser'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableFastFirstTrack2'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableDownloadLatencyLogging'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'enablePlayQualityIcon'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableFmp4AacOnPlaybackV1'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableFmp4AacOnPlaybackV2'}, {'value': '0', 'kind': 'sj#configEntry', 'key': 'iosMinimumBackgroundFetchIntervalSeconds'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'syncExperimentsToLogViaSyncService'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'androidEnableSilentFeedback'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'headphoneRecommendationNotification'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'androidEnableEntityBrowserForMediaBrowser'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'enableDynamicOffers'}, {'value': 'false', 'kind': 'sj#configEntry', 'key': 'enableDynamicOffersWithCoupons'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'disableULRReportingiOS'}, {'value': '0', 'kind': 'sj#configEntry', 'key': 'iosForegroundLocationFetchTimeoutMs'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isBtAutoplaySettingEnabled'}, {'value': 'true', 'kind': 'sj#configEntry', 'key': 'isWaitForSyncAfterSignupEnabled'}]}, 'kind': 'sj#configList'}
device_model_id: vernal-sunspot-160703-20180128085643
device_id: 6B997E6CA67120D6E6E1E4283637BAF9

https://embeddedassistant.googleapis.com/v1alpha2/projects/vernal-sunspot-160703/devices/6B997E6CA67120D6E6E1E4283637BAF9 200
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'stream I got him'}
Getting youtube link
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
['https://www.youtube.com/watch?v=k2qgadSvNyU']
['https://www.youtube.com/watch?v=k2qgadSvNyU']
ERROR:__main__:unknown url type: '/yts/jsbin/player-vflX4ueE4/en_US/base.js'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 495, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 249, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1130, in YouTube_No_Autoplay
    youtubeplayer()
  File "/home/pi/GassistPi/src/actions.py", line 1072, in youtubeplayer
    audiostream,videostream=youtube_stream_link(tracks[currenttrackid])
  File "/home/pi/GassistPi/src/actions.py", line 310, in youtube_stream_link
    video = pafy.new(url)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 92, in _fetch_basic
    smaps, js_url, mainfunc = get_js_sm(watchinfo, self.callback)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 430, in get_js_sm
    dbg_ref="javascript", file_prefix="js-")
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 367, in fetch_cached
    data = fetch_decode(url, "utf8")  # unicode
  File "/home/pi/env/lib/python3.5/site-packages/pafy/pafy.py", line 65, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-vflX4ueE4/en_US/base.js'

**Comment by Sumeetgk** [comment]
when i run the command it worked and it started the assistant and when i say stream song name then the error occurs 

File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/init.py", line 36, in autodetect
from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in 
from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

etc etc Like shown in above

**Comment by shivasiddharth** [comment]
Seems like a pafy conflict.

Open a terminal and execute the following:
`sudo pip3 uninstall mps-youtube youtube-dl`

restart your pi and try again

**Comment by Sumeetgk** [comment]
pi@raspberrypi:~ $ sudo pip3 uninstall mps-youtube youtube-dl
Cannot uninstall requirement mps-youtube, not installed




After restarting i tried again telling stream i got u and this errors comes up 
:- 

ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'stream I got you'}
Getting youtube link
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/env/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
['https://www.youtube.com/watch?v=uEJuoEs1UxY']
['https://www.youtube.com/watch?v=uEJuoEs1UxY']
ERROR:__main__:unknown url type: '/yts/jsbin/player-vflX4ueE4/en_US/base.js'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 495, in <module>
    main()
  File "/home/pi/GassistPi/src/main.py", line 249, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1130, in YouTube_No_Autoplay
    youtubeplayer()
  File "/home/pi/GassistPi/src/actions.py", line 1072, in youtubeplayer
    audiostream,videostream=youtube_stream_link(tracks[currenttrackid])
  File "/home/pi/GassistPi/src/actions.py", line 310, in youtube_stream_link
    video = pafy.new(url)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 92, in _fetch_basic
    smaps, js_url, mainfunc = get_js_sm(watchinfo, self.callback)
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 430, in get_js_sm
    dbg_ref="javascript", file_prefix="js-")
  File "/home/pi/env/lib/python3.5/site-packages/pafy/backend_internal.py", line 367, in fetch_cached
    data = fetch_decode(url, "utf8")  # unicode
  File "/home/pi/env/lib/python3.5/site-packages/pafy/pafy.py", line 65, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-vflX4ueE4/en_US/base.js'

**Comment by shivasiddharth** [comment]
Here is the fix:
1. move into the environment using:
`source env/bin/activate`
2. Execute:
`pip install youtube-dl`

Now either restart the service or manually run the main.py. This will definitely solve your issue.

**Comment by Sumeetgk** [comment]
Yes it worked Thankyou!

**Comment by shivasiddharth** [comment]
closing this..
