### ISSUE TITLE
Question ReSpeaker 2mic Hat support 

### ISSUE THREAD

**Issue by jabulonboaz** [shivasiddharth/GassistPi#171]
Hello Could u pls guide me as to what parameters to change to make the input and output audio work with a ReSpeaker 2mic Hat pls? I bought this hat and a Pi zero w. I suppose I need to change the audio HW parameters on asoundrc ?
This is the hat: 
http://wiki.seeed.cc/Respeaker_2_Mics_Pi_HAT/
https://github.com/respeaker/seeed-voicecard

**Comment by wangodanny** [comment]
Hi, also asked this question and it's been answered in this post. [https://github.com/shivasiddharth/GassistPi/issues/89](https://github.com/shivasiddharth/GassistPi/issues/89)

**Comment by shivasiddharth** [comment]
Duplicate of #89
