### ISSUE TITLE
Slow responce to youtube streaming or fmradios

### ISSUE THREAD

**Issue by adas4190** [shivasiddharth/GassistPi#172]
Hi. I did try it on ethernet aswell as on wifi. I have a decent internet speed 80+mb/s. It takes 20sec or so to stream to start. I started clean fresh latest  raspbian istall and the only thing installed is gassistpi. Could You help me pls?

**Comment by shivasiddharth** [comment]
There are two main reasons. mpv needs a buffer to provide uninterrupted audio and the second one is because of pi's processing power. Take a look at the amount of operations taking place after you give your command, you will then understand.
