### ISSUE TITLE
No such file or directory: "/root/.config/google-oauthlib-tool/credentials.json

### ISSUE THREAD

**Issue by jagan7157** [shivasiddharth/GassistPi#173]
hey sid,
         again i get this type of error 
usage: main.py [-h] [--credentials OAUTH2_CREDENTIALS_FILE] --device_model_id
               DEVICE_MODEL_ID [--project_id PROJECT_ID]
main.py: error: argument --credentials: No such file or directory: "/root/.config/google-oauthlib-tool/credentials.json"

**Comment by shivasiddharth** [comment]
This has already been discussed in #88 This is a common Raspbian error and that is why i have left #88 still open for people to see and take the necessary action.
