### ISSUE TITLE
How to turnoff the autostart?

### ISSUE THREAD

**Issue by nitrogen73** [shivasiddharth/GassistPi#175]
Im a beginner and i would like to know how to turn off the autostart at startup and how to start it manually.
Also i would like to know the status like in the terminal like as in MMM-googleassistant.
Anyone please help me?

**Comment by VinceW31** [comment]
To Stop the service press Ctrl+C to get the command prompt, then enter the following command:
sudo systemctl stop gassistpi-ok-google.service

To restart again manually enter the same command you already have at the line starting with "ExecStart=" in /home/pi/GassistPi/systemd/gassistpi-ok-google.service file.

**Comment by shivasiddharth** [comment]
stop command only temporarily stops the service. To completely disable the auto start,
`sudo systemctl disable gassistpi-ok-google.service`
