### ISSUE TITLE
Reduce the startup and feedback volume

### ISSUE THREAD

**Issue by pi3123** [shivasiddharth/GassistPi#183]
How to change the volume of just the feedback and startup sounds?

**Comment by shivasiddharth** [comment]
That is managed by Pi alsa. You need to change the pi volume.

**Comment by mraczka** [comment]
You mean changing pi volume using slider in taskbar? In my case it does nothing. 
No matter if i set the volume to alnost zero or set to maximum, reboot etc. Notifications and boot up sound are very loud.
