### ISSUE TITLE
NODE MCU issue

### ISSUE THREAD

**Issue by shan2907** [shivasiddharth/GassistPi#189]
i am able to only turn on and off device 3 , i.e. LED attached to pin three , if i say "okay google turn on wireless device 2" ,it recognises " okay google turn on wireless device to". and even if it recognises wireless device one the LED on pin D1 doesnt turn on

**Comment by shan2907** [comment]
something I noticed assistant recognises one and two ,but "3" when i say three,why is it so?

**Comment by shivasiddharth** [comment]
Inherent nature of google's speech to text conversion. I have no control over that. That is why i have made all the commands so simple that people can edit them based on their needs.
