### ISSUE TITLE
Volume of google's response is lower than the volume of notification tones

### ISSUE THREAD

**Issue by AdvaitT17** [shivasiddharth/GassistPi#19]
No its not the issue of my speaker and not even alsamixer(Volume is 100%). It happens only during answering and when I tried google-assistant-demo then it works fine...This is problem in wakeword process...

**Comment by AdvaitT17** [comment]
In sound config menu shall I change the default option Alsamixer b32... to USB Sound Card for more volume?

**Comment by AdvaitT17** [comment]
hello?

**Comment by shivasiddharth** [comment]
Alsa mixer has different playback cards to choose from. You need to choose the USB card and set volume to maximum.

**Comment by AdvaitT17** [comment]
Ok...I'm trying

**Comment by AdvaitT17** [comment]
When I changed it to USB AUDIO DEVICE and rebooted it doesn't gave any response...so I again selected b325... and rebooted so it was working but the response sound was very low...Speaker has no problem because every other thing has sufficient volume even the pop sound on wake word is more than the response give by it while using Assistant

**Comment by shivasiddharth** [comment]
share the outputs of aplay -l and arecord -l

**Comment by shivasiddharth** [comment]
open the file called assistant.py inside snowboy folder. If you scroll down, you will have a line

self.volume_percentage = 50

change that 50 to 100

**Comment by AdvaitT17** [comment]
ok...will I need to reboot

**Comment by shivasiddharth** [comment]
Yes !

**Comment by shivasiddharth** [comment]
I have made changes to the code now. I have set the volume to 80

**Comment by AdvaitT17** [comment]
I changed it but nothing happened

**Comment by AdvaitT17** [comment]
I think I have to reinstall snowboy service

**Comment by AdvaitT17** [comment]
Its not working yet

**Comment by shivasiddharth** [comment]
Reboot the Pi. Now if you use the custom wakeword, google should respond with a higher volume. Just make sure that you have selected the audio card properly.

**Comment by AdvaitT17** [comment]
bcm2835 Alsa selected as default in Audio config

**Comment by shivasiddharth** [comment]
Is google assistant responding to your custom wakeword ?

**Comment by AdvaitT17** [comment]
no its the same as previous one

**Comment by AdvaitT17** [comment]
I don't understand...even I put the system volume on mute it still responds with that low volume...How does that happen..

**Comment by AdvaitT17** [comment]
Pls help...the volume is very low.

**Comment by AdvaitT17** [comment]
This is my asound.conf

pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}
pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:1,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
    }

    }
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "dmixer"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}

**Comment by AdvaitT17** [comment]
hello?

**Comment by shivasiddharth** [comment]
Excuse me. Please learn to use this issue feature. Its not a chat window or a personal messenger and developers need time to look into issues.

**Comment by AdvaitT17** [comment]
ok...fine take your own time

**Comment by AdvaitT17** [comment]
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by AdvaitT17** [comment]
arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by shivasiddharth** [comment]
So this must be your issue. The google assistant's audio is a bit lower than the notification tones. This is because i have amplified all the audio samples  that i have given by 200% so they will be louder than the google assistant's response.

**Comment by AdvaitT17** [comment]
Then what can I do

**Comment by shivasiddharth** [comment]
In the terminal type alsamixer and then press F6 select your USB card and set the volume levels of the mic and audio out to maximum. The volume that you are controlling in the desktop is the volume of the default bcm card. Hope this clears things up.

**Comment by AdvaitT17** [comment]
Shall I make USB AUDIO CARD default setting

**Comment by AdvaitT17** [comment]
The voice which was coming before is also gone

**Comment by shivasiddharth** [comment]
Sorry i dont understand as to what you mean by "Shall I make USB AUDIO CARD default setting". How do you do that?

**Comment by AdvaitT17** [comment]
Preferences>Audio Device Settings

**Comment by AdvaitT17** [comment]
Pls help...its my project and I have to display it in the coming week

**Comment by AdvaitT17** [comment]
Is there any alternate to fix this problem?

**Comment by shivasiddharth** [comment]
For god's sake stop using this issue feature like a chat window. Just edit your comments.
If you change the preferences, the id of the cards will change after a restart in the aplay -l and arecord -l. It will not be 1, it will become 0. Then you need to change the ids in the asound.conf file.

**Comment by shivasiddharth** [comment]
Since its not an issue with the project and as it is an issue with your own settings, I am closing this....

**Comment by shivasiddharth** [comment]
@AdvaitT17 , All that i can recommend is leave the default as bcm. Change the volume of your DAC in the alsamixer like how i have alredy mentioned above.
"In the terminal type alsamixer and then press F6 select your USB card and set the volume levels of the mic and audio out to maximum. "

Your /etc/asound.conf should have
`pcm.dsnooper {
type dsnoop
ipc_key 816357492
ipc_key_add_uid 0
ipc_perm 0666
slave {
pcm "hw:1,0"
channels 1
}
}
pcm.dmixer {
type dmix
ipc_key 1024
slave {
pcm "hw:1,0"
period_time 0
period_size 1024
buffer_size 8192
rate 44100
}

}
pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "dmixer"
}
capture.pcm {
type plug
slave.pcm "dsnooper"
}
}`

and paste the same in asoundrc also. 
This will do the job. The key here is to change your DAC volume in alsa mixer.

**Comment by shivasiddharth** [comment]
As this has nothing to do with the git and as it is your audio config problem i am closing this issue now.
