### ISSUE TITLE
NameError: name 'my youtube api key' is not defined

### ISSUE THREAD

**Issue by legemulo** [shivasiddharth/GassistPi#201]
Hello! Thank you so much for this fantastic job! After so much research I finally got the Googe assistant to work on a headless raspberry pi! However, when I edited the actions.py with YouTube API and Google Play Music app password but I got an errorname not defined and the assistant would not start. Could you kindly help?

**Comment by shivasiddharth** [comment]
From what i guess, you could have forgotten to enclose them within single quotes ('). If you cna attach the log file, i can for sure, say the reason. The log file can be found in /tmp folder.

**Comment by legemulo** [comment]
That was it. I have just tried the feature and i is working! Thanks a lot! Sorry you have to deal with dummies like me!

**Comment by shivasiddharth** [comment]
Closing this issue then..
