### ISSUE TITLE
Audio prompts for device control, Pi Shutdown, servo control and wakeword detection not audible when custom wakeword is used while using HDMI for audio out

### ISSUE THREAD

**Issue by shivasiddharth** [shivasiddharth/GassistPi#23]
When using custom wakeword, snowboy.py process is one audio source and the audio prompts (aplay) in assistant.py is another audio source. As HDMI does not permit mixing of audio from two processes/sources, the prompts will not be heard. 
To compensate for that, a tiny buzz for wakeword detection has been added and in the next revison, provision for LEDs to indicate listening and speaking events will be added.

The same in not the case for the conventional "Ok-Google" hotword. The audio is controlled by a single process and hence all audio prompts will be heard even while using HDMI for audio out.

**Comment by shivasiddharth** [comment]
Closing this due to the removal of custom wakewords.

**Comment by BadFlo** [comment]
Google custom wakeword should come with next Google Home update, hopefully will also be in google-assistant project.
