### ISSUE TITLE
Help for modifying codes.

### ISSUE THREAD

**Issue by helloworld2k** [shivasiddharth/GassistPi#24]
Hi Shiva, I have added a line code to the main.py and reboot the system, but Google assistant is not working anymore, even no boot up voice, any place I need take care with?

**Comment by shivasiddharth** [comment]
What change did you make ? Manually run the assistant and post the error.

**Comment by helloworld2k** [comment]
I just added time.sleep(1)  into the code, I don't understand the problem, but after a few hour trying, it is ok now, thank you.

BTW, I cannot wake up the GAssistant by "snowboy" or "alexa" on my Pi3, everything I just followed the README

**Comment by shivasiddharth** [comment]
Interesting... Where did you add the sleep code ?
