### ISSUE TITLE
Long time response and duplicate log

### ISSUE THREAD

**Issue by teodorescusebi** [shivasiddharth/GassistPi#246]
Hi there,
I am new into this project, congrats for your work! But I have two problems: the response time is very long. After I say something, it takes a lot before the assistant comes back with an answer. The second thing is that the logs are duplicated. If I turn it on manually (using the comand /home/pi/env/bin/python -u /home/.../main.py --device_model...), every thing that appear in therminal is duplicated. Any idea about this? I think this may be the reason for the long time response.
Thank you!

**Comment by shivasiddharth** [comment]
Response time depend on the network and pi CPU resources. What you are seeing is just duplicate print commands. It has nothing to do with the response time.

**Comment by teodorescusebi** [comment]
I have the Pi 3, so the top one, and the internet connection is very good. I tried installing only the Google Assistant and it works without any issue. I will try to look in the project for details that I am maybe missing. About the duplicated print commands, you have any idea why it's happening? There is no duplicated python command to print any message twice.
