### ISSUE TITLE
Spotify Playback On The Device

### ISSUE THREAD

**Issue by adas4190** [shivasiddharth/GassistPi#249]
Hi, Great work and Thank You for Your hard work!!!!
On the latest sdk it is possible to stream spotify but only to other/chromecast enabled devices. Google assistant says that it is not possible to do it here but she can play it on other connected devices and it works, it can play on predefined device with no error. My question is is there any way to enable that playback on the device it self?

Thank You.

**Comment by shivasiddharth** [comment]
Emulation of Pi as a cast receiver is not possible. Instead i will try and add the Spotipy package that was previously mentioned in the issue #177 Keep an eye on that issue. Closing this.
