### ISSUE TITLE
Cannot issue a broadcast message

### ISSUE THREAD

**Issue by adas4190** [shivasiddharth/GassistPi#252]
It was possible on previous sdk. now I've got an answer that there is no GH in my network. I have 2, and it used to work. Is there anything that can be done?

Thank You.

**Comment by shivasiddharth** [comment]
Wrong Git. Fundamental SDK issues to be opened/discussed in SDK's git. Just curious, did you authenticate Pi credentials using the same account as the Home?

**Comment by adas4190** [comment]
I did use the same account to authenticate.

**Comment by shivasiddharth** [comment]
@adas4190 , Has this issue been addressed at the upstream SDK repo ?

**Comment by adas4190** [comment]
Yes but I didn't get any satisfactory response 😔

**Comment by shivasiddharth** [comment]
I guess the latest SDK 0.5.0 has solved this. Please feel free to reopen if i was wrong.
