### ISSUE TITLE
using GassistPi with a different user impossible

### ISSUE THREAD

**Issue by totomaze** [shivasiddharth/GassistPi#255]
Hi,

I would like to try GassistPi and already change a lot of hardcoded link from /home/pi to home/MyUser, but there are everywhere.

It would be good if it can be set has an environment variable like GASSISTPI_HOME=/home/pi

Great work by the way :)

**Comment by shivasiddharth** [comment]
Work is in progress to extend this project to other SBCs and other OSes. Once that commit is merged, the username will not be hardcoded.

**Comment by k15866** [comment]
Hey,

Can I just check that it is currently impossible to work this on different users, even if I go into individual files and change all /home/pi to /home/MyUser? I have only read this after troubleshooting multiple issues on installation. I've hit a wall when trying to manually start the assistant as per readme instructions.

I get a traceback which eventuates in:
ImportError: No module named 'yaml'

Despite changing the .py files in /GassistPi/src to look for config.yaml to include MyUser directory, I still come up with the same error. Is there more I need to change, or is there simply no work around and I need to install on /pi directory.

I'm still learning so please be kind :) Thanks
