### ISSUE TITLE
Why my Google 'muted'

### ISSUE THREAD

**Issue by afroguys** [shivasiddharth/GassistPi#262]
Hello guys....
this git still alive or dead??

**(env) pi@raspberrypi:~ $ googlesamples-assistant-hotword --device_model_id gamirror-30ff9-gamirror-xe6yb2
device_model_id: xxx-30ff9-gamirror-xxxxxx
device_id: xxxxxxxxxxxxxxxxxxxxxxxxx

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'who are you'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'what time now'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}
**

**Comment by shivasiddharth** [comment]
How long have you been around in this git ? You are saying as though you posted something ages ago and no one responded. Ideal way to check whether a git is alive or dead is by checking the last commit date.

And by the way, if it was muted, it would not listen to your request. If you look carefully it says muted is False, meaning it's not muted.
