### ISSUE TITLE
Can I install Google Vision and Voice on one device?

### ISSUE THREAD

**Issue by Curious-Nikhil** [shivasiddharth/GassistPi#267]
**Google Vision SDK** is interesting, so I was thinking of installing this on pi, which already has **GAssist**.
Is it possible to **install** without running into errors?

Your **thoughts** and **suggestion** on this, plz @shivasiddharth 
Many Thnx! :D

**Comment by shivasiddharth** [comment]
Vision SDK is meant for android devices as i stated in one of my previous comments.
