### ISSUE TITLE
Not checking if pip is installed in gassist-installer-pi3.sh  

### ISSUE THREAD

**Issue by blackwiz4rd** [shivasiddharth/GassistPi#270]
Hi,
I have seen this error is common: https://imgur.com/a/llYrW
It's probably because you haven't told users to install pip before running.
If it's possible you could include installation in the script.
Thanks for your great work!

**Comment by blackwiz4rd** [comment]
I also had to do this after a clean install:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

**Comment by valascus** [comment]
Wich distro did you install?

**Comment by valascus** [comment]
Which*

**Comment by blackwiz4rd** [comment]
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l

I am just assuming that was the problem because without doing that I couldn't go on with the installation.

**Comment by shivasiddharth** [comment]
The error is due to network issues that i have already pointed out in #182 It has nothing to do with pip and language.

**Comment by valascus** [comment]
Also, GAssistPI doesn't support the Lite version of Raspbian. You will have lots of problem to solve if you really want to go that way

**Comment by shivasiddharth** [comment]
@valascus , Two updates backed the fixed the installer script to accomodate Lite versions. So there should be no issues.
@blackwiz4rd , The lite versions do not come with pip, that is why i have added pip in the system requirements. So that will be installed.

**Comment by valascus** [comment]
Really?!?
A few months ago i tried to use lite and, even with much sacrifice, couldn't make it fully functional. I will test it out then :D
