### ISSUE TITLE
Raspberry not showing in google home app devices

### ISSUE THREAD

**Issue by blackwiz4rd** [shivasiddharth/GassistPi#274]
Hi,
I have seen from your youtube video that you the raspberry pi lists on your home app devices. In my case it doesn't. Do you know how this problem could be solved? Thanks a lot ;)

**Comment by aandroide** [comment]
before opening the app assistant on your phone, you need to set the English language for the phone after open the assistant app and your devices will appear

**Comment by blackwiz4rd** [comment]
Hi,
I have the language set in English US, does it have to be UK?

**Comment by shivasiddharth** [comment]
1. You need to have an android device, not apple.
2. Android device should be running Android 7 and above.
3. Device language should be set to English US.
4. Pi gets listed in Assistant App and not in Home App.

**Comment by blackwiz4rd** [comment]
Sorry for me being a noob. I had download 'Google home app' and not 'Google assistant app'

**Comment by kodxana** [comment]
Do you know any way to acces assistant app from pc?
