### ISSUE TITLE
bug say("text") in pushbutton.py

### ISSUE THREAD

**Issue by aandroide** [shivasiddharth/GassistPi#276]
hi, in pushbutton, I noticed that in any function integrates the function say ("text") and has finished speaking, when I press the button to give the commands again, he does not listen, start to listen when I press the button again.

**Comment by aandroide** [comment]
I do not think it's a problem of say why in hotword everything works fine, it does so only in pushbutton. it would seem that it does not listen to the first push of the button after the stream commands, by pressing a second time the button returns to work

**Comment by shivasiddharth** [comment]
I am sorry but unable to understand as to what the issue here is. Can you try and explain it a bit more.

**Comment by aandroide** [comment]
simply if I say stream "song title" and then stubborn the song with the button, when I press the pushbutton to give a new command, the first time it flashes it sounds but does not listen to me, as soon as it stops flashing, I'll reset the button and go back to work correctly. I noticed that this defect only occurs in functions that integrate the say function ("text")

**Comment by aandroide** [comment]
the problem disappeared with the update.
I close
