### ISSUE TITLE
google assistant service is responding before snowboy

### ISSUE THREAD

**Issue by moham96** [shivasiddharth/GassistPi#28]
Hi,
I'm running Gassistpi on raspberrypi 3, according to the readme file I should run snowboy and google assistant service at the same time but sometimes google assistant takes the lead and respond before snowboy, for example when i say "Alexa" google assistant responds "I'm flattered but that's not me, I'm your google assistant" i don't know how to reproduce this issue, it happens randomly, this happened three times for me already

**Comment by shivasiddharth** [comment]
That will happen if you trigger google assistant and then say "Alexa" as a query. Are you using HDMI out for audio?

**Comment by moham96** [comment]
@shivasiddharth I haven't setup any other mean to trigger google assistant(gpio button) other than the voice activation, and no i'm not using hdmi out, i'm using audio jack for speakers and usb mic

**Comment by shivasiddharth** [comment]
Please understand, Ok-Google does not respond to alexa. What i am trying to say is, ALexa would have triggered the assistant and saying alexa again will give "I'm flattered but that's not me, I'm your google assistant"

**Comment by moham96** [comment]
@shivasiddharth ok I understand now ,you mean i might have said "Alexa" two times quickly, thank you for clearification
