### ISSUE TITLE
Solution for "trigger" keyword not recognized

### ISSUE THREAD

**Issue by iamericha** [shivasiddharth/GassistPi#280]
Hi there, 

I had a hard time getting my NodeMCU to switch with the "Trigger" keyword.  I went into your main.py file and added a keyword "node" and had that call your ESP function in the actions.py file directly and it works perfectly now.

For example, my phrase would be: "NODE LAMP ON" and it'll switch the pin I had connected to my lamp on.

If not a project wide change, maybe other people who may be having issues can adopt this change.

Best and thanks for all the hard work!  This project rocks.

**Comment by shivasiddharth** [comment]
I shall mark this issue as a tip and close. In that way, people can search by tags.
