### ISSUE TITLE
snowboy

### ISSUE THREAD

**Issue by karrarmaher** [shivasiddharth/GassistPi#281]
What about the  Multiple Custom Wakeword Triggers for Headless Google Assistant﻿?

**Comment by rammere** [comment]
I can not see snowboy script where it is ?

**Comment by codelock13** [comment]
Please other posts the repo owner clearly said it is coming in next update
as it was not working properly with new SDK if you have fix to it please
pull request

**Comment by rammere** [comment]
Hi Sorry I did not notice that , though it will be better to be mentioned in the Documentation ,anyway I will try to find a solution .
:)

**Comment by shivasiddharth** [comment]
Duplicate of #136
