### ISSUE TITLE
YouTube streaming

### ISSUE THREAD

**Issue by chathurangawijetunge** [shivasiddharth/GassistPi#285]
More then 50% times assistant reboots after saying "getting youtube link"
Why is That?

**Comment by patricktelling** [comment]
GassistPi saves a log file in the /tmp directory. You can use it to figure out what is causing the crash, or post your log file here.

**Comment by chathurangawijetunge** [comment]
Why is this?

**Comment by shivasiddharth** [comment]
This is not what I would expect to see in case of an error. Looks like you have restarted the Pi. The logs will be deleted on shutdown/restart. If you want to post an error log, the log file should be added here before shutting down or restarting the Pi. 

And please attach the log, don't paste it.

**Comment by chathurangawijetunge** [comment]
If #287 is "Zombie Process" in linux.
Then this is also one of those zombies too...

**Comment by shivasiddharth** [comment]
@chathurangawijetunge ,  If you are unaware of something and if someone gives a pointer to learn should either try and understand or request clarification instead of making fun. This kind of behaviour is unappreciated.  As a result, i am closing all your existing issues.
