### ISSUE TITLE
If "chromecast" is spoken, application terminates

### ISSUE THREAD

**Issue by lottaboost** [shivasiddharth/GassistPi#286]
If you say "ok google", then say anything with the word chromecast, the application exits.

**Comment by shivasiddharth** [comment]
I have assigned a custom action with chromecast keyword. Open the main.py and scroll over to line 381 that says `if 'chromecast'.lower() in str(usrcmd).lower():` and comment the lines from 381 through 386.

**Comment by lottaboost** [comment]
Nevermind, I had to set my chromecast ip address in the actions.py file.  I would have figured it out faster, but the chromecast did respond correctly even without injecting it's ip address into actions.py.

**Comment by shivasiddharth** [comment]
The current SDK supports chromecasting out of the box, you dont need the custom action and hence, comment out those parts.

**Comment by lottaboost** [comment]
Yeah, I commented out those lines.  And it still worked, I guess that custom action can be removed now.  thanks

**Comment by lottaboost** [comment]
Now, hopefully they will update their SDK so pandora and music stuff can be used on device itself :)

**Comment by shivasiddharth** [comment]
Issue resolved, closing this thread.
