### ISSUE TITLE
Slow Hotword answer on Lite

### ISSUE THREAD

**Issue by valascus** [shivasiddharth/GassistPi#288]
Hi!
As i said on a issue, i'm testing now the GAssistPi on Raspbian Lite. For now, and for the things that i use, it works well, but i noticed a thing. When i say "Ok Google", the answer from the RaspBerry is way more slower (like 1s) then when i had the Raspbian (not lite). 
Any clue on this?

**Comment by shivasiddharth** [comment]
For all i know, it could be a network thing and you need to re-create the exact network traffic conditions to ascertain that LITE is indeed slower.  Actually speaking, LITE should be a tad faster. This is exactly not an issue and for non-issue posts, you can use the gitter.
