### ISSUE TITLE
Where Can I find The Action.py

### ISSUE THREAD

**Issue by ashishsandhu** [shivasiddharth/GassistPi#29]
Where Can I find The Action.py, I Need To Add Some Commands and Change Some Of The Results It Gives.  I Have Installed THE OS you provided, ""voice-recognizer-raspi/src/action.py "" But Where Can I Finf This action.py?

**Comment by shivasiddharth** [comment]
In the latest update, I have created an actions file, but copy pasting AIY actions will not work. for a better understanding of the new actions file please follow this video. https://youtu.be/-MmxWWgceCg
