### ISSUE TITLE
There is no place to write the chromecast IP in the actions.py

### ISSUE THREAD

**Issue by kengberg** [shivasiddharth/GassistPi#304]
There is no place to write the chromecast IP in the actions.py

**Comment by shivasiddharth** [comment]
Ip address to be entered in Line 1292 : https://github.com/shivasiddharth/GassistPi/blob/68ddae12c611697e06e29707c8f760941b356212/src/actions.py#L1292

The exact line of code keeps changing that is why its not mentioned in the Readme. Moreover chromecasting is now supported natively by Google, you dont need the custom action, you can comment the custom action lines in main.py #286
