### ISSUE TITLE
How to undo installation.

### ISSUE THREAD

**Issue by supreme83** [shivasiddharth/GassistPi#306]
I have removed the files fro gassistpi but am still getting errors durign staartup. How should this be properly removed from my linux installation so i can get sound bac working via hdmi?

**Comment by shivasiddharth** [comment]
Audio config files have nothing to do with the assistant. Start by removing the assistant service using:
sudo systemctl disable "whichever service you enabled"
Then if you can use the requirements file to remove the packages.

**Comment by supreme83** [comment]
Considering that during your configuration instructions it clearly says to change the audio device and makes the AIY speaker the default playback device,  I'd say it has plenty to do with the audio configuration hence why I'm trying to remove this and get back to my standard linux installation before assist pi changed my audio to the AIY speaker. Thanks
