### ISSUE TITLE
How can i start a conversation with GassistPi?

### ISSUE THREAD

**Issue by outtacontrol216** [shivasiddharth/GassistPi#308]
the say(words) together with the  if name.lower() in phrase command is pretty easy to use. but how can i write/start a conversation?

like:
if 'temperature' in phrase:
      say("What temperature do you want to know?)
      - with_follow_on_turn -
      me: temperature from dinner room
      say("the temperature in dinner room is %s" % temp_dinnerroom)

**Comment by shivasiddharth** [comment]
Check this part https://github.com/shivasiddharth/GassistPi/blob/642941a9ff87ed268b726ef13dbbf4f5b9b85300/src/main.py#L355
