### ISSUE TITLE
AttributeError on "hotword.py" while installing Google Assistant with GassistPi

### ISSUE THREAD

**Issue by vikaskarunakaran** [shivasiddharth/GassistPi#312]
While installing GassistPi with Google Assistant 0.1.1 getting attribute error in hotword.py.

Issue also reported in [https://github.com/googlesamples/assistant-sdk-python/issues/233](url)

Testing the installed google assistant. Make a note of the generated Device-Id
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 128, in main
    Assistant.__version_str__())
AttributeError: type object 'Assistant' has no attribute '__version_str__'
[googleassistant.log](https://github.com/shivasiddharth/GassistPi/files/1917964/googleassistant.log)

**Comment by shivasiddharth** [comment]
The project has been updated to SDK 0.5.0 that should fix this. If its not, then please feel free to reopen.
