### ISSUE TITLE
[Question] Any way to change the intro and hotword detection sounds?

### ISSUE THREAD

**Issue by Triscuit47** [shivasiddharth/GassistPi#314]
Hi,
I would like to know if there's a way to change the sound it outputs through the speakers whenever the hotword is detected or when the Pi boots up. 

Thank you.

**Comment by schromotion** [comment]
You can add new .wav files you'd like to use into /home/pi/GassistPi/

Change line 138 in /src/main.py to point at the conversation start sound file you'd like. 
"/home/pi/GassistPi/sample-audio-files/Fb.wav"->"/home/pi/GassistPi/sample-audio-files/_newfile.wav_"

Same thing in line 277 for the start up sound. 

Hope that helps!

**Comment by Triscuit47** [comment]
Thanks for the info :D
