### ISSUE TITLE
Waking when hot word not said

### ISSUE THREAD

**Issue by cyn5351** [shivasiddharth/GassistPi#32]
I hear my assistant going off all the time. Seems to be recording
How can I limit this to just ok Google¿

**Comment by shivasiddharth** [comment]
Do you hear that startup tone or something else ? You can disable custom wakeword using the following command.
sudo systemctl disable snowboy.service

**Comment by cyn5351** [comment]
I hear the tone. I will give the command below a try.thxOn Oct 11, 2017 8:14 AM, shivasiddharth <notifications@github.com> wrote:Do you hear that startup tone or something else ? You can disable custom wakeword using the following command.
sudo systemctl disable snowboy.service
