### ISSUE TITLE
Adding few question and answers to GassistPi

### ISSUE THREAD

**Issue by LebronReddy** [shivasiddharth/GassistPi#321]
Hi Sid, I'm not a programmer and am finding it difficult in adding a set of question and answers in the Gassistpi scripts. I want the assistant to respond according to the fed questions and answers. Could you please tell me how to do that?         ( sample instance: "Hey Google! can you tell me what is the teacher teaching me now?" ----" Its a physics class and the teacher is teaching you Electromagnetism")

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi#custom-conversations Project has been updated with the ability to have custom conversations.
