### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by iamhollis84** [shivasiddharth/GassistPi#326]
chmod +x /home/pi/GassistPi/audio-drivers/USB-DAC-HDMI/scripts/install-usb-mic-hdmi not in directory

**Comment by jptrsn** [comment]
You're missing the .sh file extension.

`sudo chmod +x /home/pi/GassistPi/audio-drivers/USB-DAC/scripts/install-usb-dac.sh `

**Comment by iamhollis84** [comment]
Will that work if I’m using a usb mic but the hdmi audio?

**Comment by jptrsn** [comment]
Ah, was a copy/paste error; should have been:

`sudo chmod +x /home/pi/GassistPi/audio-drivers/USB-MIC-HDMI/scripts/install-usb-mic-hdmi.sh  `

**Comment by iamhollis84** [comment]
It says not a directory

**Comment by jptrsn** [comment]
Did you install git and clone the repository?

**Comment by iamhollis84** [comment]
wget https://github.com/shivasiddharth/GassistPi then apt-get install raspberrypi-kernel. Did I miss something?

**Comment by shivasiddharth** [comment]
wget is not the command to clone the repo. Please see the README doc.
