### ISSUE TITLE
Autostart 

### ISSUE THREAD

**Issue by aprooooo** [shivasiddharth/GassistPi#327]
There is no place for project Id in auto start file only device model id

[Unit]
Description=Google Assistant-Voice
Wants=network-online.target
After=network-online.target

[Service]
Environment=VIRTUAL_ENV=/home/pi/env
Environment=PATH=/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'saved-model-id'

WorkingDirectory=/home/pi/
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target

**Comment by shivasiddharth** [comment]
You do not need to add the project-id.
