### ISSUE TITLE
source code string cannot contain null bytes

### ISSUE THREAD

**Issue by aprooooo** [shivasiddharth/GassistPi#329]
I have this error 

pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --de
evice_model_id 'aproo-dcf0e-302283925457'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 17, in 
    from kodijson import Kodi, PLAYER_VIDEO
  File "/home/pi/env/lib/python3.5/site-packages/kodijson/__init__.py", line 2, in 
    from .kodijson import *  # NOQA
  File "/home/pi/env/lib/python3.5/site-packages/kodijson/kodijson.py", line 3, in 
    import requests
ValueError: source code string cannot contain null bytes
pi@raspberrypi:~ $

**Comment by shivasiddharth** [comment]
Please do not open multiple issues for the same issue... This is the same as #325  The model-id is dubious. I have set the model id to be generated based on time and date and from the looks of it, Your model-id does not seem to be generated by the installer script.

**Comment by aprooooo** [comment]
@shivasiddharth
I'm sorry for that 
But The model id generated by script. 
And when I restarted I got a taskbar issues

**Comment by shivasiddharth** [comment]
For general issues like those related to taskbar please use the gitter or raspberrypi's forums.
