### ISSUE TITLE
Add support for google actions

### ISSUE THREAD

**Issue by pradeep-pioneer** [shivasiddharth/GassistPi#330]
Hello,

This is quite nice project that you created, I wanted to fork it but then I found the hard coded parsing stuff in the code and decided not use it. I have started something from the scratch but I don't parse user speech by hard coded rules, rather I am using google actions api (which is not very powerful right now but will be polished), the NLP happens on the cloud and I get clear commands, intents and arguments from the actions api.

You can check out my repo and share any feedback that you might have.
https://github.com/ProofOfConcepts/MyPi

Cheers!
Pradeep

**Comment by shivasiddharth** [comment]
Please use Gitter Page that i have created for all non-issue related posts or queries. Thanx.
