### ISSUE TITLE
Gpio controls aren't working...

### ISSUE THREAD

**Issue by PavanSN** [shivasiddharth/GassistPi#34]
I said ok,Google and said the command many times but unable to toggle the gpio.. plz help.

**Comment by shivasiddharth** [comment]
What response did you get ?

**Comment by PavanSN** [comment]
It just says, I'm working on it...

**Comment by shivasiddharth** [comment]
it means, its not recognizing your trigger word.. Start the assistant manually from terminal say the command for triggering and see what it is detecting. the detected text will appear as test in the terminal.

**Comment by PavanSN** [comment]
It detected the word and said I can't help you at the moment... Plz help

**Comment by shivasiddharth** [comment]
google has some issues with their servers Please take a look at this
https://developers.google.com/assistant/sdk/release-notes
googlesamples/assistant-sdk-python#119

**Comment by shivasiddharth** [comment]
Even if the demo recognizes the trigger word it cannot execute the actions..
