### ISSUE TITLE
Radio stations with *.pls url links

### ISSUE THREAD

**Issue by pere66** [shivasiddharth/GassistPi#350]
First I like to thank you shivasiddharth for all this you do for us.

Some radio stations with pls playlist url link wont play at all with mpv player or play just for second or two.

1. First reason is connected with mpv unsafe playlist...

Warning
The way mpv uses playlist files via --playlist is not safe against maliciously constructed files. Such files may trigger harmful actions. This has been the case for all mpv and MPlayer versions, but unfortunately this fact was not well documented earlier, and some people have even misguidedly recommended use of --playlist with untrusted sources. Do NOT use --playlist with random internet sources or files you do not trust!
Playlist can contain entries using other protocols, such as local files, or (most severely), special protocols like avdevice://, which are inherently unsafe.
Solved with --load-unsafe-playlists option
source https://mpv.io/manual/master/

2. Second reason is of unknown duration of pls file message, cannot seek this file.
Solved with --no-ytdl option, explanation on same site  https://mpv.io/manual/master

Solved with adding two more parameters after starting mpv in actions.py and its look like this
os.system('mpv --load-unsafe-playlists --no-ytdl --volume='+str(startingvol)+' '+station+' &')

**Comment by shivasiddharth** [comment]
I have ported the music playback to vlc, so this is no longer valid.
