### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by bimbim2401** [shivasiddharth/GassistPi#351]
hi

Any information of how can I change the language of gassistpi ?

**Comment by aandroide** [comment]
you have to open the google assistant app go to settings, devices and you should see the device you have registered, then click on and search for the language

**Comment by bimbim2401** [comment]
hi,

sorry but what is the google assistant app, i am on a raspberry and i am not sure to understand what to do.

**Comment by aandroide** [comment]
it also works on ios.cerca in the appstore google assistant and installs the application

**Comment by aandroide** [comment]
ok, if you've solved close the problem

**Comment by bimbim2401** [comment]
yep thanks you ;-)
