### ISSUE TITLE
Google assistant demo error

### ISSUE THREAD

**Issue by PavanSN** [shivasiddharth/GassistPi#36]
Recently I've installed latest RaspberryEcho stretch in my raspi 3, after following your steps carefully I got an error saying that

Google-assistant-demo: error --credentials: no such file or directory: "home/pi/. Config/google-oauth-tool/credentials.json"

**Comment by PavanSN** [comment]
Sorry raspberry pi stretch

**Comment by shivasiddharth** [comment]
It means that you have not authenticated the assistant using the assistant.json credentials file. Re run the installer and authenticate.
