### ISSUE TITLE
line 63: 5264 Segmentation fault 

### ISSUE THREAD

**Issue by killerman6565** [shivasiddharth/GassistPi#369]
### Describe the bug:
```
error after authentication code is entered, new to coding please help
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No
yes
### 2. Is the issue related to assistant installation ?
Yes/No
yes
## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
/home/pi/GassistPi/scripts/gassist-installer-pi3.sh: line 63: 5264 Segmentation fault                   googlesamples-assistant-hotword --project_id $projid --device_model_id $modelid
```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by aandroide** [comment]
https://github.com/shivasiddharth/GassistPi/issues/366
