### ISSUE TITLE
use gpio

### ISSUE THREAD

**Issue by electrotuto** [shivasiddharth/GassistPi#37]
Hello,
 I want to use all gpio of raspberry. how to do? 
for example: when i say :" ok google, turn on pump1" the gpio n°1 goes to high.
salusations and thanks

**Comment by shivasiddharth** [comment]
You need to add the GPIOs and device names in the actions.py file. I have written comments in the file, which are self-explanatory. Also, please beware, you cannot use all GPIOs for controlling devices.
