### ISSUE TITLE
Control a lamp Bulb already compatible with Google Home

### ISSUE THREAD

**Issue by datrix88** [shivasiddharth/GassistPi#370]
HI!
Is there a way to control, through Google Assistant SKD, a lamp bulb already compatibile with Google Home?

Here's an example of lamp:

https://www.amazon.com/Assistant-Amazon-Multicolor-Dimmable-Required/dp/B07B4SMYBH/ref=sr_1_6?ie=UTF8&qid=1527844800&sr=8-6&keywords=bulb+google+assistant

And if yes how can i do to interface this lamp with the skd?

**Comment by aandroide** [comment]
once you register the lamp on the assistant app you can also automatically control it from the sdk

**Comment by datrix88** [comment]
How I can do to register the lamp on the assistant?
I didn't find the Raspberry on the Google Home App...

**Comment by aandroide** [comment]
https://www.amazon.com/Assistant-Amazon-Multicolor-Dimmable-Required/dp/B07B4SMYBH/ref=sr_1_6?ie=UTF8&qid=1527844800&sr=8-6&keywords=bulb+google+assistant

Works with Google Home
The Smart Bulb works with Google Assistant to manage your devices through Voice Control.
Assign a name to each Smart Bulb and communicate each Bulb by name when making a voice command.

Hey Google, turn on the bedroom
Hi Google, set bedroom to 20%
Hey Google, set the bedroom to green color

**Comment by shivasiddharth** [comment]
@datrix88 , for non issue related discussion, please use the gitter page. I am closing this.
