### ISSUE TITLE
Google assist not responding for demo code.

### ISSUE THREAD

**Issue by harishperla09** [shivasiddharth/GassistPi#375]
Following appeared after installing the demo code. I tried many times but the same appears everytime.
 
ON_CONVERSATION_TURN_STARTED
ON_RESPONDING_STARTED:
  {"is_error_response": true}
ON_RESPONDING_FINISHED
ON_ASSISTANT_ERROR:
  {"is_fatal": false}

Pl. help me.

**Comment by shivasiddharth** [comment]
Closing this because it does not follow the issue template.
The template has been put in place to save everybody's time.

**Comment by harishperla09** [comment]
Give me the template
