### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Rooster69** [shivasiddharth/GassistPi#379]
Hi Sid,
I'm in the process of updating GassistPi, is there a script of updating GassistPi without re-installing?

**Comment by shivasiddharth** [comment]
You can use [this](https://github.com/shivasiddharth/GassistPi/blob/update-script/GassistPi-04-June-2018-update.sh). But you should already be in SDK 0.5.0 or in another words should have installed the 24/25th May update from scratch.
