### ISSUE TITLE
No confirmation beep after saying "ok, Google" 

### ISSUE THREAD

**Issue by aro28** [shivasiddharth/GassistPi#385]
Hi guys! When i say "Ok, Google" it should play Fb.wav confirmation beep file from /home/pi/GassistPi/sample-audio-files/ directory. But now, it works without beeping. Who know how can i fix it.

Thanks in advance.

**Comment by shivasiddharth** [comment]
If you are using the demo, you will not hear the beep. For better understanding, it would be nice to mention the board that you are using along with the audio peripherals. As it is, the issue that you have opened conveys very little info.

**Comment by aro28** [comment]
As I know I do not use Demo. How can I check it?
I use USB mic and USB sound adapter. 
I configured below audio settings. 
3.4. USB MIC AND AUDIO JACK users,
sudo chmod +x /home/pi/GassistPi/audio-drivers/USB-MIC-JACK/scripts/usb-mic-onboard-jack.sh  
sudo /home/pi/GassistPi/audio-drivers/USB-MIC-JACK/scripts/usb-mic-onboard-jack.sh  


speaker-test -t wav command is passed successfully.

**Comment by shivasiddharth** [comment]
Frankly, i have no idea as to why that is happening. All that i can say is, if you are using USB Mic and USB sound card, you have got the configuration scripts wrong. The scripts that you have used are for Pi's onboard jack.

**Comment by aro28** [comment]
Ok. Will try to setup with onboard audio tomorrow. 
Thanks!

**Comment by aro28** [comment]
HI @shivasiddharth 
I reconfigured for USB mic and onboard audio jack. It's still there's no confirmation beep.

**Comment by aro28** [comment]
Fixed. It was an audio settings issue. :)
