### ISSUE TITLE
Feature request : neopixel indicator

### ISSUE THREAD

**Issue by VH-Tech** [shivasiddharth/GassistPi#391]
hi,
I wanted a feature in which 

1) If hot word is detected and the google assistant starts listening then there should be a certain animation with the neopixel

2) if  the request is being processed then also their should be an animation

**Comment by shivasiddharth** [comment]
Already exists. Please go through the readme..

**Comment by VH-Tech** [comment]
I know that this feature already exists but it's for arduino  and I am requesting for Raspberry pi

**Comment by shivasiddharth** [comment]
Without Arduino if you use the neopixels, the onboard audio jack on pi will not work properly. Both use pwm.

**Comment by VH-Tech** [comment]
ok

**Comment by cbinde** [comment]
For users without the need of the internal jack (e.g i am using usb sound device), it would be great to use the Neopixel directly connected to the Pi. Is there a chance to get that feature?
