### ISSUE TITLE
new update google assist not install

### ISSUE THREAD

**Issue by ankurshah963** [shivasiddharth/GassistPi#406]
```
previous version install in mu rpi2 and work complete fine. 
but new release version not install


i will follow all steps but last 
```
i will enterd my project id correct but
**

**[" Enter the modelid that was generated in the actions console: "]** 

how to find that ???

=========== pls saw my error ============

Registering...Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 133, in main
    device_model_id, device_id)
  File "/home/pi/env/lib/python3.5/site-packages/google/assistant/library/device_helpers.py", line 76, in register_device
    raise RegistrationError(r, device_model_id)
google.assistant.library.device_helpers.RegistrationError: Failed to register device PERMISSION_DENIED (403): Could not create the device instance. You don't have permission to get device model gapi. Make sure you registered this device model under your project gapi-195009.

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes
## If answer to question 2 is Yes, then paste the contents of the terminal below.

i hope reply me and resolve that

thank you 
ankur shah

**Comment by ashishverma2614** [comment]
i am also getting the same error as you get earlier it was working but after last updtae it is not installing correctly
