### ISSUE TITLE
How to change the trigger word and make custom command. 

### ISSUE THREAD

**Issue by AkterAhsan** [shivasiddharth/GassistPi#41]
where i can find the trigger word and change it to something else. and also how i make new trigger word for new custom command .. thanks in advance.

**Comment by shivasiddharth** [comment]
Please go though the section called "VOICE CONTROL of GPIOs, SERVO and Pi SHUTDOWN" in the readme..Trigger words have to be assigned in main.py file and the functions in the actions.py file.

**Comment by shivasiddharth** [comment]
Closing this..
