### ISSUE TITLE
Spotify responds with "Getting music links" and does nothing

### ISSUE THREAD

**Issue by clarkycal** [shivasiddharth/GassistPi#417]
### Describe the bug:
```
Spotify responds with "Getting music links" and does nothing
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
Here is the chat with me and the assistant, basically it says "Getting music links and then does not play the music.":
```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play car playlist from Spotify"}
stopping vlc
Getting music links
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
car playlist
1
car playlist
XXXTENTACION Jocelyn Flores

```

**Comment by clarkycal** [comment]
Uh, nevermind seems to be working, only with one playlist though.. Does it only work for playlists rather than just a song.

**Comment by romeok01** [comment]
I have the same problem, dont play radio and spotify.

In the player.json i have:
[2, 46, "on", "Radio"]

In the .trackqueue.json  i have:
"http://stream3.polskieradio.pl:8900/listen.pls"

I write my client id and client secret i username in config.yaml file.

Google Assistant say: Thats music links and music not playing.

**Comment by clarkycal** [comment]
Add a Google api-key to the config that should fix sporting as it uses YouTube

**Comment by aandroide** [comment]
even with the api youtube key inserted I get the same errors as above

**Comment by aandroide** [comment]
@clarkycal but in the username, did you put the name of the spotify playlist folder?

**Comment by romeok01** [comment]
I have the same problem, i have playlist, user name, client_id,  client_secret and when i say: play my playlist from spotify, assistant say: thats its music links and music not play.

**Comment by clarkycal** [comment]
@romeok01 It only works with YOUR playlists, not others you follow. So make a new test playlist, and call it (For example) "Test Playlist" then ask the assistant to "Play 'Test Playlist' from Spotify" should work.

**Comment by romeok01** [comment]
Dont work, maybe must premium account in Spotify.

**Comment by valascus** [comment]
I have a premium Spotify account, Youtube Stream works(google api works), it makes requests to Spotify, but does nothing and restart's GAssistPI.

**Comment by Arul-** [comment]
I was trying my email id as the spottily username, and it did not work. It is not that clear in the instructions as well

Open Spotify music on the browser and go to your library. Here is my URL for example

    https://open.spotify.com/user/21l6p3aqb37r4t5lceuppymcq/playlist/0TQz1jpv02FCKjldReto0n

My user id is **21l6p3aqb37r4t5lceuppymcq**

Find yours and use that as your username in the `config.yaml`  and then Spotify starts working!  :)

**Comment by valascus** [comment]
Thanks for your answer, Arul, but my link shows as: 
https://open.spotify.com/user/valascus/playlist/5nOnJOKadol7DcwaSLmFcb?si=Vqkl8GMkRpud7Cyz6tzQWA

So, my user is valascus?
That's what i have at config.yaml, but still no sucess

**Comment by Arul-** [comment]
@valascus then that part is set right, a problem still may be elsewhere, we have to keep digging

**Comment by valascus** [comment]
It makes requests... I can see in the graphs from Spotify developers page, but... Same issue.

**Comment by Arul-** [comment]
@valascus upon further digging, I found the following help

- [ ] make sure your Spotify playlist is public and 
- [ ] it's not muted in the web player

**Comment by valascus** [comment]
Thank you once again.
Both of that requeriments were and are checked.

**Comment by valascus** [comment]
Where did you get that "username"
My "username", as far as i know, is valascus. That's what appears at profile and when i generate a link for a playlist.

**Comment by aandroide** [comment]
the link is: https://www.spotify.com/it/account/overview/
to get the username once logged in you must then copy it to config.yaml

**Comment by aandroide** [comment]
@valascus verify the user name better, usually they are numbers and letters or numbers only or try to register in spotify with the same email you use for gassistpi and create a new app as explained in the readme and then access the link I mentioned above. As soon as I logged in, the page with the username in numbers appeared. can you attach a screenshot?

**Comment by valascus** [comment]
None of them worked.
In fact, GAssistPi didn't restart, which is good, but not playing anything tho.
Here's a screenshot of my spotify profile: https://prnt.sc/k5qdvv

**Comment by valascus** [comment]
It is valascus. It get's the Playlist. It says "1" (position where the playlist is when getting it). It was 5 and 6 before. I just deleted all the other playlists. It get's data. With the "users" u said, it gives 0.

**Comment by aandroide** [comment]
At this point I would try to redo the registration to spotify from scratch

**Comment by valascus** [comment]
But i need premium to use this feature, which i would not have if i changed my account.

**Comment by aandroide** [comment]
@valascus I have no premium and it works great.

**Comment by valascus** [comment]
Rly? 
I thought u needed to be premium for spotify developers dashboard. 
I'll try it in a sec.

**Comment by aandroide** [comment]
let's go by exclusion:
but does the strem from youtube work for you? have you enabled the bees from the console?

**Comment by valascus** [comment]
Doesnt work with a new account either. As in the main account, it does find the playlist, but nothing else.

Youtube Stream works fine.
Enable the bees?? What's that??

**Comment by valascus** [comment]
If u mean API's, yeah. i did. As i just said, youtube works.

**Comment by aandroide** [comment]
ok 
when you edit the config.yaml file, stop the assistant and restart to activate the new changes did you do it?

**Comment by valascus** [comment]
Of course.

**Comment by aandroide** [comment]
ok, can you attach your actions.py file and your config.yaml?

**Comment by valascus** [comment]
[Spotify.zip](https://github.com/shivasiddharth/GassistPi/files/2189903/Spotify.zip)

I let my personal configs there so u can actually test it.

**Comment by aandroide** [comment]
I have pasted your files in my project and are playing:
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "Play best playlist from Spotify"}
stopping vlc
Getting music links
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of say.mp3 finished.
best playlist
1
best playlist
The Chainsmokers Something Just Like This
[02ac6970] pulse audio output error: PulseAudio server connection failure: Connection refused
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}

**Comment by aandroide** [comment]
ok google Play best playlist from Spotify

**Comment by valascus** [comment]
So, the problem is not at the configuration itself. What could it be?

**Comment by valascus** [comment]
As you can see, nothing special here...

`Jul 12 18:39:09 raspberrypi python[12166]: ON_END_OF_UTTERANCE
Jul 12 18:39:10 raspberrypi python[12166]: ON_RECOGNIZING_SPEECH_FINISHED:
Jul 12 18:39:10 raspberrypi python[12166]:   {"text": "play best playlist on Spotify"}
Jul 12 18:39:10 raspberrypi python[12166]: stopping vlc
Jul 12 18:39:10 raspberrypi python[12166]: Getting music links
Jul 12 18:39:11 raspberrypi python[12166]: High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
Jul 12 18:39:11 raspberrypi python[12166]: #011version 1.23.8; written and copyright by Michael Hipp and others
Jul 12 18:39:11 raspberrypi python[12166]: #011free software (LGPL) without any warranty but with best wishes
Jul 12 18:39:12 raspberrypi python[12166]: Directory: /tmp/
Jul 12 18:39:12 raspberrypi python[12166]: Playing MPEG stream 1 of 1: say.mp3 ...
Jul 12 18:39:12 raspberrypi python[12166]: MPEG 2.0 L III cbr32 24000 mono
Jul 12 18:39:13 raspberrypi kernel: [785813.980735] Voltage normalised (0x00000000)
Jul 12 18:39:13 raspberrypi python[12166]: [0:01] Decoding of say.mp3 finished.
Jul 12 18:39:13 raspberrypi python[12166]: best playlist on spotify
Jul 12 18:39:14 raspberrypi python[12166]: 1
Jul 12 18:39:14 raspberrypi python[12166]: best playlist
Jul 12 18:39:14 raspberrypi python[12166]: ON_CONVERSATION_TURN_FINISHED:
Jul 12 18:39:14 raspberrypi python[12166]:   {"with_follow_on_turn": false}`

**Comment by aandroide** [comment]
not on but from spotify

**Comment by valascus** [comment]
Shouldn't mather, as he recognizes it.
But w8

**Comment by valascus** [comment]
No. Same. Issue.

**Comment by aandroide** [comment]
the configuration is correct.
you can attach
gassistpi.log that find folder temp

**Comment by aandroide** [comment]
I do not like this message:
 raspberrypi kernel: [785813.980735] Voltage normalised (0x00000000) 

have you tried to change power supply?
it could go haywire with voltage drops

**Comment by valascus** [comment]
For some reason, it worked now.
Yes, i need to change it. The one that i bought should be fitting the Raspberry PI just fine, as i bought it just for that purpose. It was announced as "for RaspBerry Pi 3". It has an imbebbed Switch to turn on/off the PI, but only 5V, and 2.5A

**Comment by aandroide** [comment]
if the problem should come back replace the power supply. the scripts are ok

**Comment by sanderthierens** [comment]
hi
i have a problem to. I have a chrome cast called bedroom tv and when i say " hey google, play spotify on my bedroom tv" it says " getting music links" but my assistant on my raspberry pi restarts itsef and I cant ask her things for a short while until I hear the start sound off the assistant. spotify plays normal. alo that " getting music links" is rally annoying to can I turn it off?

**Comment by valascus** [comment]
You can't say that sentence. It won't recognize.
You must say: Ok Google, Play "NAME OF THE PLAYLIST" from Spotify.
Only that.

It only works with YOUR playlists.

**Comment by sanderthierens** [comment]
oke, but I still have that problem that my assistant stops working and restart it self after I say Ok Google, Play "NAME OF THE PLAYLIST" from Spotify.  And it is only with spotify not when i say Ok Google, play " name of a song" on youtube. And can I turn off the words she says "getting music links"   every time i ask her to play something. also I cant find the config.yaml file.

ps: I am new to this world, so my apologies when I ask silly questions.

**Comment by valascus** [comment]
ok. That's your problem then. You can't find config.yaml?
If you followed the intructions, it should be at /home/pi/GassistPi/src/config.yaml.

You must setup a google api to get from youtube and define your spotify credentials.

**Comment by joerivd1** [comment]
hallo I have the same problem as sanderthierens. afther I say Ok Google, Play "NAME OF THE PLAYLIST" from Spotify. the assistant responds with getting music links and plays the playlist but afther it says getting music liks? my assistant don't respond to ok google or hey google for a small time and then i hear the same sound when I turn on the raspberry pi 3 ( the sound that the assistant is starting and ends with "hi"). so i assume that the assistant crashes and itself restart. afther that sound i can start to ask things again. can somone help me with this problem?

**Comment by shivasiddharth** [comment]
@sanderthierens and @joerivd1 It can mean only one thing, the spotify credentials have not been entered properly in the config.yaml.

**Comment by joerivd1** [comment]
@shivasiddharth  thanks it worked for me I made a small mistake with the cllient secret. one more question? is it posible to not hear the ' getting music links' ?

**Comment by shivasiddharth** [comment]
i have intentionally placed it to know when error is happening. if you dont want to hear that, search for a line that starts with "say" within the functions assigned for spotify and comment that.

**Comment by joerivd1** [comment]
how do you mean exactly with functions assigned for spotify? where can i find that

**Comment by aandroide** [comment]
@joerivd1 in actions.py comment on the line 1303

**Comment by joerivd1** [comment]
ef spotify_playlist_select(phrase):
    trackslist=[]
    currenttrackid=0
    idx=phrase.find('play')
    track=phrase[idx:]
    track=track.replace("'}", "",1)
    track = track.replace('play','',1)
    track = track.replace('from spotify','',1)
    track=track.strip()
    say("Getting music links")
    print(track)
    playlists,num=scan_spotify_playlists()
    if not num==[]:
        for i in range(0,num):
            print(str(playlists['Playlists'][i][1]).lower())
            if track in str(playlists['Playlists'][i][1]).lower():
                trackslist=playlists['Playlists'][i][2]
                break
        if not trackslist==[]:
            vlcplayer.media_manager(trackslist,'Spotify')
            vlcplayer.spotify_player(currenttrackid)
    else:
        say("Unable to find matching playlist")

**Comment by shivasiddharth** [comment]
@joerivd1 , comment those lines with `say` if you do not want to hear voice prompts. You can comment it by adding a # symbol at the start of the line.

**Comment by sanderthierens** [comment]
@shivasiddharth  so how do I do it properly in the config.yaml.
I have now and the username is correct from spotify

#Spotify credentials. Register for a spotify developer and get the credentials.
Spotify:
  client_id: 7405d02b211a4163ae21fcfbdbba0482
  client_secret: 5e6bb44c4e084fbe9e3f42eb7901819d
  username: 11169079112

I checked again and everyting is correct. and problem is still happening
that the assistant restart it self

**Comment by shivasiddharth** [comment]
@sanderthierens , Two things. 
1.The credentials should be entered within the quotes just like how you had them in the unedited config.yaml file. 
2. I am not sure, if spotify assigns usernames with numbers (but i could be wrong), so double check your spotify username in https://www.spotify.com/account/overview/.

**Comment by sanderthierens** [comment]
@shivasiddharth I was not sure eather before but I asked and is was indeed my username, sotify generate the username themselve now, no idea why. do I need to restart the pi3 afther I changed somthing in config.yaml file?

**Comment by aandroide** [comment]
@shivasiddharth 
I confirm that with a Free account, spotify assigns a username that contains numbers and letters

**Comment by shivasiddharth** [comment]
@sanderthierens , you need to restart the assistant. Restart of Pi is not required.

**Comment by oscarrc** [comment]
Same issue here, I've checked my username, api keys and the playlist is not muted on the web player (as someone suggested before). The music does not play (Youtube streaming works fine).

```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play party playlist from Spotify"}
stopping vlc
Obtener enlaces de música
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:02] Decoding of say.mp3 finished.
party playlist
5
party
favoritos
favoritos
favoritos
favoritos
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}
```

**Comment by shivasiddharth** [comment]
@oscarrc , You have got the syntax wrong. It should be just "Play party from Spotify".

**Comment by oscarrc** [comment]
@shivasiddharth my fault, it works, I've misunderstood the syntax. Thanks

**Comment by mr2wei** [comment]
I'm getting segmentation fault
