### ISSUE TITLE
Trigger Shutdown command not working

### ISSUE THREAD

**Issue by Fringo9** [shivasiddharth/GassistPi#419]
Hi, first of all thank you for your awesome work! The Google Assistant works perfectly except of the command "Trigger Shutdown" that does nothing.

I tried as you suggested in issue #251 to run manually the assistant and it understands "trigger shutown" but doesn't execute the command. 

Any idea how I can track down the problem?

> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>    {"text": "trigger shutdown"}
> ON_CONVERSATION_TURN_FINISHED:
>    {"with_follow_on_turn": false}

Thanks, Fringo9

**Comment by shivasiddharth** [comment]
As you can see from the customization, the command has been assigned as "shut down" with space, but the assistant is deciphering it as shutdown without space. So you need to change the "shut down" in actions.py to "shutdown"
