### ISSUE TITLE
Issue while playing music

### ISSUE THREAD

**Issue by santoshmohan** [shivasiddharth/GassistPi#42]
While playing music, I am facing issues:
```
def YouTube(phrase):
      print(phrase)
      idx=phrase.find('play')
      print(idx)
      track=phrase[idx:]
      track=track.replace("'}", "",1)
      track = track.replace('play','',1)
      track=track.strip()
      print(track)
      global playshell
      if (playshell == None):
        playshell = subprocess.Popen(["/usr/local/bin/mpsyt",""],stdin=subprocess.PIPE ,stdout=subproce$
      print("Playing: " + track)
      playshell.stdin.write(bytes('/' + track + '\n'))
    playshell.stdin.write(bytes('1' + '\n')) 
    playshell.stdin.flush()

```
If pharse is "Play shape of you", it fails while stdin.write and below is the exception

```
shape of you
Playing: shape of you
Traceback (most recent call last):
  File "/home/pi/main.py", line 76, in <module>
    main()
  File "/home/pi/main.py", line 71, in main
    YouTube(str(usrcmd).lower())
  File "/home/pi/actions.py", line 51, in YouTube
    playshell.stdin.write(bytes('/' + track + '\n'))
TypeError: string argument without an encoding
pi@raspberrypi:~ $ Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by shivasiddharth** [comment]
Any reason for adding `playshell.stdin.write(bytes('1' + '\n')) `  in the youtube function ?

**Comment by santoshmohan** [comment]
As ` playshell.stdin.write(bytes('/' + track + '\n1\n'))` thing wasn't working, I had to split them in to two.
But still it didn't work

**Comment by shivasiddharth** [comment]
I tested the  "Play shape of you" command and i can confirm that it works. Please remove the changes that you made and make sure that the code is formated properly and try again. Sometimes due to slow internet connection, i might take some time.

**Comment by santoshmohan** [comment]
<img width="627" alt="screen shot 2017-10-28 at 10 10 54 pm" src="https://user-images.githubusercontent.com/6982545/32133911-06b8ba2c-bc2d-11e7-9c49-25ac8b8563e8.png">
Still I am facing the same issue. I am using same code.

**Comment by shivasiddharth** [comment]
What is "the same code" ? Your edited version or the unedited version? It will fetch only the best and topmost rest from YouTube search. It's not Google to fetch some random song. If it did not find a matching result it will return an error.. some song is too vague query.

**Comment by santoshmohan** [comment]
Issue resolved by changing the below:
`playshell.stdin.write(bytes('/' + track + '\n1\n','utf-8'))`
