### ISSUE TITLE
execute a program

### ISSUE THREAD

**Issue by kumarsatish23** [shivasiddharth/GassistPi#421]
### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
Yes

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```
i don't say it as a bug the thing is that i want to execute a program (say"abc.py") from a particular path when i speak out a key word
```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by kumarsatish23** [comment]
help me

**Comment by aandroide** [comment]
use the chat for these non-installation questions 
https://gitter.im/GassistPi/Lobby/

**Comment by shivasiddharth** [comment]
Please use gitter for general queries. Closing this.
