### ISSUE TITLE
GAssistPi on Bluetooth speaker with built-in mic?

### ISSUE THREAD

**Issue by AKnightWing** [shivasiddharth/GassistPi#422]
I connected my Raspberry Pi 3B+ to my bluetooth speaker Bose SoundLink Revolve+, and can confirm that audio was playing successfully through it when watching videos on youtube(for eg.). I wanted to use GAssistPi on this and thus followed the tutorial in the readme, however was stuck at the installation of audio config files. I tried all of them, but none seemed to work.
Thanks for the help.

**Comment by shivasiddharth** [comment]
For non issue posts/queries use gitter.
