### ISSUE TITLE
(google assistant using raspberry pi 3)  hi sir my google assistant is working properly only for  4 to 5 questions and after  it is getting off , i have to restart it again. please help me to work continuously till i off.

### ISSUE THREAD

**Issue by praveen04n** [shivasiddharth/GassistPi#425]
### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Closing this issue for not using the issue template properly.
