### ISSUE TITLE
Push button does not stop music/radio playback on AIY Hat config since June 16 update

### ISSUE THREAD

**Issue by iamericha** [shivasiddharth/GassistPi#428]
### Describe the bug:
```
I am a AIY Hat user.  I had the GAssist installed from a build from March.  I recently updated seeing your June 16 update.  Since there was no update script, I just went through the installation process again.

Afterwards, everything seems to be working correctly but the Stop Button no longer works.  I have enabled the stopbutton.service and tried starting the stopbutton.service manually but it still doesn't stop my music/radio playbacks.

I've checked my connections just in case to see if any of the wires were disconnected but they are not.  I am not sure how to trouble shoot this right now.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No
### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

**Comment by aandroide** [comment]
@shivasiddharth 
It's a problem in the code that I've already reported too. Ps changes the title to be clearer with Stop Button does not work

**Comment by shivasiddharth** [comment]
@iamericha , Does the vocal "stop" command stop the music?

**Comment by iamericha** [comment]
Hi Sid, the vocal stop does work for the YouTube stream music but does not work for the radio stream. The stop button did used to stop both. I still have my previous image where the stop button did work but just haven’t had time to load that back on to see if the stop button works with the previous image. I will try that when I get the chance.

**Comment by aandroide** [comment]
@shivasiddharth With the previous image it works. It's a problem between the gpio library and the new vlc library. the stop command called vocally stops the music but if you press the button does nothing. Does Sid work for you?

**Comment by oscarrc** [comment]
Same issue here.

**Comment by shivasiddharth** [comment]
Can you ppl test this fix out:
1. Stop the stopbutton service.
2. Replace the existing main.py with this https://github.com/shivasiddharth/GassistPi/blob/stopbutton-fix-patch/src/main.py

Start the main.py manually or as the usual service and check the stopbutton functionality. No need to restart or run the old stopbutton service.

**Comment by aandroide** [comment]
hi sid, I noticed a bug, I asked to play a song and the first time the stopbutton worked by stopping the music.
I requested a second time to play a song and the stopbutton does not work.
I restarted and did the same joke, the first time it worked and the second time no.

**Comment by shivasiddharth** [comment]
I have fixed the issue, try pulling the latest files from master.

**Comment by aandroide** [comment]
great job Sid, now it works
