### ISSUE TITLE
News playback

### ISSUE THREAD

**Issue by sigfgfgf** [shivasiddharth/GassistPi#43]
how can i make assistant read rss feeds from a website like timesofindia

**Comment by shivasiddharth** [comment]
http://www.markwilliamdavies.co.uk/blog/?p=12 use this as reference to create your own actions.

**Comment by sigfgfgf** [comment]
actor.add_keyword(_('the news'), ReadRssFeed(say, "http://feeds.bbci.co.uk/news/rss.xml?edition=uk#",10))

how do i change this line for actions.py ??

**Comment by shivasiddharth** [comment]
Podcasts and music streaming will be added in the net update.... Closing this now.
