### ISSUE TITLE
GassistPi setup issue Failed to execute operation: Bad message

### ISSUE THREAD

**Issue by ffawazz** [shivasiddharth/GassistPi#431]
when I run the below I get failures

pi@ttt:~/GassistPi/systemd $ sudo systemctl enable gassistpi-ok-google.service

Failed to execute operation: Bad message

pi@ttt:~/GassistPi/systemd $ sudo systemctl enable gassistpi-push-button.service

Failed to execute operation: Bad message

pi@ttt:~/GassistPi/systemd $

https://github.com/shivasiddharth/GassistPi

**Comment by shivasiddharth** [comment]
Commands are executed incorrectly.

**Comment by ffawazz** [comment]
Can you help me by showing the correct commands. I'm a beginner 👶

Thanks
