### ISSUE TITLE
Google Assistant Demo test - Illegal instruction

### ISSUE THREAD

**Issue by tiancaipipi110** [shivasiddharth/GassistPi#437]
After entered authorization code, it showed message below: 
`Testing the installed google assistant. Make a note of the generated Device-Id  /home/pi/GassistPi/scripts/gassist-installer-pi-zero.sh: line 56: 19372 Illegal instruction     googlesamples-assistant-pushtotalk --project-id $projid --device-model-id $modelid`

And of course it won't respond to 'Hey Google, Set volume to maximum" voice command. Thanks for the help.

**Comment by vincentcapicotto** [comment]
I have the same issue with a pi1, no problem with a pi2

**Comment by sanderthierens** [comment]
the pi1 doesnt work with the google assistant

**Comment by shivasiddharth** [comment]
@tiancaipipi110 , can you please use the issue template?
