### ISSUE TITLE
HEADLESS AUTOSTART on BOOT SERVICE SETUP problem

### ISSUE THREAD

**Issue by sanderthierens** [shivasiddharth/GassistPi#438]
greatings,

Afther I typed the command "sudo  /home/pi/GassistPi/scripts/gassist-installer-pi-zero.sh" everything went well and the demo worked perfect and the hotword worked also perfect. But then i went to the next step and closed the terminal.
the next step was HEADLESS AUTOSTART on BOOT SERVICE SETUP and i dit everyting but when i restart the raspberry and used the "oke google " or "heey google" hotword nothing happens 

i have a raspberry pi 3 B+

**Comment by shivasiddharth** [comment]
Please use the issue template.
