### ISSUE TITLE
Italian language info

### ISSUE THREAD

**Issue by jacopomarcovaldi** [shivasiddharth/GassistPi#44]
Hi,
Google Assistant is rolling out in Italy (it will understand italian language).
I am wondering if i have to change your code of if this project will understand italian without any code review.
Thank you.

Jacopo

**Comment by shivasiddharth** [comment]
As long as things dont change here, https://developers.google.com/assistant/sdk/release-notes there is no need to change any codes in the project. If there is an update listed in that page, then, i may have to see as to what has changed and then suggest/do the suitable changes. Most of the updates are back-end so it should not be a issue..

**Comment by jacopomarcovaldi** [comment]
Thank you for your quick reply! :) 
Jacopo
