### ISSUE TITLE
audio configuration with voice bonnet

### ISSUE THREAD

**Issue by SesiluNarud** [shivasiddharth/GassistPi#444]
Step 3 has voice hat, but new AIY kit (V2) uses voice bonnet. Does this change anything or do you still use the audio configuration instructions for the voice hat even though the hardware is different?

**Comment by shivasiddharth** [comment]
Its all the same. You can use the same config for bonnet as well.

**Comment by kevintee23** [comment]
Apologies for the duplicate. Did not check the "closed" issues.

I tried installing the audio config files as per AIY-HAT instructions. When i do the speaker test, there is no sound coming out from the speaker. On terminal, this is what i see:-

speaker-test 1.1.3

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 2048 to 16384
Period size range from 1024 to 1024
Using max buffer size 16384
Periods = 4
was set period_size = 1024
was set buffer_size = 16384
 0 - Front Left
Time per period = 1.135040
 0 - Front Left
Time per period = 1.468758
 0 - Front Left
Time per period = 1.452825
 0 - Front Left
Time per period = 1.455535
 0 - Front Left
Time per period = 1.478584

This continues even after several minutes until i cancel the service, and i get:-

^CWrite error: -4,Interrupted system call
xrun_recovery failed: -4,Interrupted system call
Transfer failed: Interrupted system call

**Comment by shivasiddharth** [comment]
@kevintee23 , you should restart the Pi at the indicated instances. Hope you have done that. if yes, then you should hear white noise when you run the speaker test. If you dont hear that, then please check the speaker's hardware connection. Then run `sudo nano ~/.asoundrc` from the terminal and verify if the contents are the same as what i have given in `home/piGassistPi//audio-drivers/AIY-HAT/scripts/asound.conf` file

**Comment by sethcohn** [comment]
I had an issue with the tests in https://github.com/shivasiddharth/Assistants-Pi/blob/master/scripts/audio-test.sh  on the bonnet
specifically: the recording wouldn't work with this line:
`  arecord -d 10 -D hw:0,0 -r 48000 -f S32_LE -c2 /home/pi/mic-test.wav`
until I changed it to be S16_LE

Before the error was
```
Select your audio config that you used:
1) AIY-HAT-or-CUSTOM-HAT
2) USB-DAC-or-USB-SOUNDCARD-or-USB-MIC

Please select an option [1-2] 1
Selection: AIY-HAT-or-CUSTOM-HAT
=============Recording Mic Audio Sample=============
Recording WAVE '/home/pi/mic-test.wav' : Signed 32 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1299: Sample format non available
Available formats:
- S16_LE

```

Playing the voice works fine (as does the playing of the recording once the change was made).  What is the correct value for the bonnet?  (Possibly different from the HAT?)
