### ISSUE TITLE
stream youtube

### ISSUE THREAD

**Issue by ibrahim5alil** [shivasiddharth/GassistPi#445]
### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by ibrahim5alil** [comment]
plz if anyone can help me 
i need to know what to edit and how in action.py to stream youtube

**Comment by shivasiddharth** [comment]
Everything is given in detail in README. If you need further help for non-issue things, please use gitter.

**Comment by ibrahim5alil** [comment]
thank's for your reply sir, i will
