### ISSUE TITLE
hotword issue

### ISSUE THREAD

**Issue by serhatkimya** [shivasiddharth/GassistPi#450]
thank you very much for added to hotword shivasiddharth.i have a problem, i tried three different hotwords and work perfectly but for example when listening to music, assistant choose the words and getting listening mode.it is so sensitive. i tried long wakeword but problem same.
thanks for everything.

**Comment by shivasiddharth** [comment]
Sorry i am not able to understand.  You mean the custom hotwords are sensitive that even music is triggering them ? You can adjust the sentivity of the hotwords while creating them in snowboy or try changing the sensitivity here https://github.com/shivasiddharth/GassistPi/blob/e251b17f44bf82746cde2e373f26306017c5d6c7/src/main.py#L151

**Comment by serhatkimya** [comment]
yes, you are right, i will try thanks.

**Comment by serhatkimya** [comment]
i solved my problem by recording clear sound and everything is ok
