### ISSUE TITLE
The arlam sound is too small

### ISSUE THREAD

**Issue by BarryAlle** [shivasiddharth/GassistPi#461]
Hi,My arlam sound on GassistPi is too small even though i both turn max volume on raspberry and tell google turn to the highest level still not work.

Please help me

**Comment by aandroide** [comment]
hello, for the moment the raspberry is not a device that you can 'add in the google home app and therefore you can not change the volumes of timere alarms and alarms unlike google home google as described here: https://support.google.com/googlehome/answer/7550530?

**Comment by BarryAlle** [comment]
Oh thanks you
