### ISSUE TITLE
Why do we need nmap installation?

### ISSUE THREAD

**Issue by rasppicuibap** [shivasiddharth/GassistPi#479]
Hi friend,
Could you explain why we need nmap while installing GassistPi

> Setting up libenca0:armhf (1.19-1) ...
Setting up python-webencodings (0.5-2) ...
Setting up mplayer (2:1.3.0-6) ...
Setting up libxslt1-dev:armhf (1.1.29-2.1) ...
Setting up libpcap0.8:armhf (1.8.1-3) ...
Setting up libavdevice57:armhf (7:3.2.10-1~deb9u1+rpt2) ...
**_Setting up nmap (7.40-1) ..._**
Setting up ndiff (7.40-1) ...
Setting up ffmpeg (7:3.2.10-1~deb9u1+rpt2) ...
Setting up python-html5lib (0.999999999-1) ...
Setting up mpv (0.23.0-2+deb9u2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...

Thanks!

**Comment by shivasiddharth** [comment]
Please use the gitter for non-issue queries and doubts.
