### ISSUE TITLE
Music stream ends abruptly

### ISSUE THREAD

**Issue by theboss1956** [shivasiddharth/GassistPi#49]
I have been happy with the project so far, but whenever I play music, it plays a little more than halfway through, and then stops. Running on RPI3. Any solutions?

**Comment by shivasiddharth** [comment]
its an inherent issue with the youtube downloader and vlc player..refer https://github.com/mps-youtube/mps-youtube/issues/543
i need some time to work on the fix. changing player to mpv doesn't seem to work..

**Comment by theboss1956** [comment]
Can you update me when it’s fixed?

**Comment by shivasiddharth** [comment]
Hello,
This is let you know that i have fixed the abrupt stoppage issue today. I tested the playback and almost music played smoothly for about 2 hours. If you try the installation again, it should be fine..

**Comment by theboss1956** [comment]
Thanks! Will close
