### ISSUE TITLE
gpio doesnt respond 

### ISSUE THREAD

**Issue by chinmay007rh** [shivasiddharth/GassistPi#501]
I am using raspberry pi 3, when i ask gassistpi to   trigger "bathroom lights on" (gpio 13) it reply's turning on lights ,but relay doesnt turn on( i have connected vcc and ground to pin no 2,6 respectively . i havent made any changes to config.yami file yet. what should i do.

**Comment by shivasiddharth** [comment]
I have very limited info here. Working with that here are my thoughts.
1. For successful triggering data lines should be atleast 75% of the supply voltage levels.  The Pi GPIOs are 3.3v which fall well below the 75% limit.
2. I am not sure about the brand of relay module that you are using. The sainsmart relay modules are known to work in reverse logic (High is Off and Low is On).

PS: Any non-issue related queries/discussion/help to be posted in gitter.
