### ISSUE TITLE
PulseAudio error

### ISSUE THREAD

**Issue by DarPe07** [shivasiddharth/GassistPi#504]
pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/pushbutton.py --project-id asistentepivirtual  --device-model-id asistentepivirtual        [01491590] pulse audio output error: PulseAudio server connection failure: Connection refused

**Comment by shivasiddharth** [comment]
This has been discussed already in a number of issues previously ( #494 #451 #449 #416 #413 ). This is why sticking to the issue template helps.

> Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No
