### ISSUE TITLE
Add custom conversations

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#506]
Hi shiva,first of all i would like to say well done,i have done such a great work!!!!
second i just to ask you that con i creat a custom answer li google aiy voice kit.I have try using iftt to creat one but it just can creat only one so... Please answer me as soon as possible.

Thanks

**Comment by shivasiddharth** [comment]
Do you have a link to the AIY Kit's custom conversation ? I will see what they have done and if possible release it in the next update.

**Comment by BarryAlvord** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=114&t=189054

**Comment by BarryAlvord** [comment]
i hope this usefull::)

**Comment by shivasiddharth** [comment]
Not a big  deal. Will add it in the next update.

**Comment by BarryAlvord** [comment]
But just show us somewhere to edit to creat our own thanks

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi#custom-conversations Project has been updated with the ability to have custom conversations.
