### ISSUE TITLE
Location name Bug

### ISSUE THREAD

**Issue by matrix1000** [shivasiddharth/GassistPi#513]
Hi have a problem with locationnames.
If more than one are the same, the last char changes.
Version: v1.6.0-beta3
example devices.csv: 
```
1,"test01",192.168.0.254,admin,,bulb_1,aaaa
2,"test02",192.168.0.254,admin,,bulb_1,aaaa
3,"test03",192.168.0.254,admin,,bulb_1,aaaa
4,"test04",192.168.0.254,admin,,bulb_1,aaaa

```
Here a screenshot of the List
![ta](https://user-images.githubusercontent.com/1917331/45076624-26d38680-b0eb-11e8-80f4-514dbcc4299f.PNG)

**Comment by shivasiddharth** [comment]
What is this ? I dont think this is even a part of this project. Sorry I am unable to understand as to what you are trying to tell.

**Comment by matrix1000** [comment]
Oh, I am so sorry, wrong git repo.
