### ISSUE TITLE
Volume of assistant response really low

### ISSUE THREAD

**Issue by theboss1956** [shivasiddharth/GassistPi#54]
Hey, me again.

Just wanted to know if their is any way to boost the volume of the assistant’s response. I ask this because when I set an alarm, I can’t hear it, even when music is not playing. I can’t turn up the volume because that would mean that I would have to change the volume every time I switched between music listening and alarm setting.

**Comment by shivasiddharth** [comment]
Unfortunately, there is nothing that can be done at the moment. process wise audio volume control is not feasible now.

**Comment by theboss1956** [comment]
Alright then.

**Comment by shivasiddharth** [comment]
I am closing this issue for now, but if come up with something to control the media audio alone, will update you here.
