### ISSUE TITLE
GassistPi automatically go to mute mode in latest update

### ISSUE THREAD

**Issue by kumarmohan7** [shivasiddharth/GassistPi#540]
Hi Shiva,

Latest GassistPi is automatecaly goto mute mode when i add Custom Wakeword in config.yaml ,

then i remove the Custom Wakeword in config.yaml , now allso same issue is there...

how to solve this issue...

ON_MUTED_CHANGED:
  {"is_muted": true}
ON_MUTED_CHANGED:
  {"is_muted": true}
ON_MEDIA_STATE_IDLE
ON_MEDIA_STATE_IDLE
ON_START_FINISHED
ON_START_FINISHED

Thanks,
Mohankumar

**Comment by duall** [comment]
Added some custom wake words, it starts muted as well, okay google no reaction

**Comment by shivasiddharth** [comment]
Ok google will not work only under two circumstances:
1. If you muted it using a pushbutton.
2. if you have disabled it in config.yaml

Other than these two cases, Ok Google will work normally. And remember that Pi Zero does not have Ok Google wakeword support.

**Comment by duall** [comment]
My GPIO headers are hidden so there was no way i was able to press them.
config.yaml must've have triggered it
I have solved it by opening rpi and shorting GPIO pin to mute and then again to unmute. There was no hidden .mute file in home directory.

**Comment by saiedmethal** [comment]
i am also facing the same problem mic goes mute, and no .mute file also When i MANUALLY START THE ASSISTANT this shows up as error 

INFO:gmusicapi.Mobileclient1:failed to authenticate
[0177bf78] pulse audio output error: PulseAudio server connection failure: Connection refused
[017b3508] pulse audio output error: PulseAudio server connection failure: Connection refused
USB-MIC-HDMI
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 64, in <module>
    from indicator import assistantindicator
  File "/home/pi/GassistPi/src/indicator.py", line 51, in <module>
    GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
RuntimeError: Failed to add edge detection

**Comment by ankurshah963** [comment]
> i am also facing the same problem mic goes mute, and no .mute file also When i MANUALLY START THE ASSISTANT this shows up as error
> 
> INFO:gmusicapi.Mobileclient1:failed to authenticate
> [0177bf78] pulse audio output error: PulseAudio server connection failure: Connection refused
> [017b3508] pulse audio output error: PulseAudio server connection failure: Connection refused
> USB-MIC-HDMI
> Traceback (most recent call last):
> File "/home/pi/GassistPi/src/main.py", line 64, in 
> from indicator import assistantindicator
> File "/home/pi/GassistPi/src/indicator.py", line 51, in 
> GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
> RuntimeError: Failed to add edge detection


same as problem here

**Comment by Kintounn** [comment]
> > i am also facing the same problem mic goes mute, and no .mute file also When i MANUALLY START THE ASSISTANT this shows up as error
> 
> INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
> INFO:gmusicapi.Mobileclient1:version: 11.0.3
> INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
> INFO:gmusicapi.Mobileclient1:initialized
> INFO:gmusicapi.Mobileclient1:logged out
> INFO:gmusicapi.Mobileclient1:failed to authenticate
> [02fe11f0] pulse audio output error: PulseAudio server connection failure: Connection refused
> [03021b68] pulse audio output error: PulseAudio server connection failure: Connection refused
> USB-MIC-JACK
> Traceback (most recent call last):
> File "/home/pi/GassistPi/src/main.py", line 64, in 
> from indicator import assistantindicator
> File "/home/pi/GassistPi/src/indicator.py", line 51, in 
> GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
> RuntimeError: Failed to add edge detection
> 
> same as problem here

I have the as issue as well, the headless auto start doesn't work and I can't manually start the assistant as well.

**Comment by Kintounn** [comment]
> Are you guys using some HAT connected to the pi?

I'm using the Respeaker 4 mic array.

The assistant only works when sudo  ./GassistPi/scripts/gassist-installer-pi3.sh

**Comment by saiedmethal** [comment]
usb mic and HDMI for speaker

**Comment by ankurshah963** [comment]
dear sir,

please note.....

fresh install assistance working OK. but after restart there problem are create. manually start assistance ,but same issues generate.

> rpi connect USB mic and auxiliary output sound..
> rpi not connected other hardware to GPIO pins. 
> i am using raspberry pi 2 model B.

**Comment by shivasiddharth** [comment]
@Kintounn  You have got the audio scripts wrong.  If you used my Respeaker installation, `USB-MIC-JACK` will be shown as Respeaker-4-Mic.

**Comment by shivasiddharth** [comment]
@saiedmethal and @ankurshah963  I need some more details. Which version of operating system are you guys using?  Have you changed the Pins in config.yaml file ? Have you enabled 1 wire in Pi interfacing options?

**Comment by Kintounn** [comment]
I tried both drives, but none of them worked.

On 27 Oct 2018, at 2:46 am, shivasiddharth <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kintounn<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKintounn&data=02%7C01%7C%7C8656e0ae4b104a43ce7808d63b5a33f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636761655931149403&sdata=z9z%2BtezijL37PfNYIiQPZuTu7O5zXyR8GgSQVJHTokw%3D&reserved=0> You have got the audio scripts wrong. If you used my Respeaker installation, USB-MIC-JACK will be shown as Respeaker-4-Mic.

**Comment by BriKKou** [comment]
Hello,
Same problem for me. Using Voice HAT on PI3

```
Oct 26 16:02:22 raspberrypi systemd[1]: gassistpi-ok-google.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 16:02:22 raspberrypi systemd[1]: gassistpi-ok-google.service: Unit entered failed state.
Oct 26 16:02:22 raspberrypi systemd[1]: gassistpi-ok-google.service: Failed with result 'exit-code'.
Oct 26 16:02:23 raspberrypi systemd[1]: gassistpi-ok-google.service: Service hold-off time over, scheduling restart.
Oct 26 16:02:23 raspberrypi systemd[1]: Stopped Google Assistant-Voice.
Oct 26 16:02:23 raspberrypi systemd[1]: Started Google Assistant-Voice.
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:version: 11.0.3
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:initialized
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:logged out
Oct 26 16:02:30 raspberrypi python[3405]: INFO:gmusicapi.Mobileclient1:failed to authenticate
Oct 26 16:02:31 raspberrypi pulseaudio[3524]: [pulseaudio] sink.c: Default and alternate sample rates are the same.
Oct 26 16:02:31 raspberrypi pulseaudio[3524]: [pulseaudio] source.c: Default and alternate sample rates are the same.
Oct 26 16:02:31 raspberrypi pulseaudio[3524]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Oct 26 16:02:31 raspberrypi pulseaudio[3524]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Oct 26 16:02:32 raspberrypi python[3405]: AIY-HAT
Oct 26 16:02:32 raspberrypi python[3405]: Traceback (most recent call last):
Oct 26 16:02:32 raspberrypi python[3405]:   File "/home/pi/GassistPi/src/main.py", line 64, in <module>
Oct 26 16:02:32 raspberrypi python[3405]:     from indicator import assistantindicator
Oct 26 16:02:32 raspberrypi python[3405]:   File "/home/pi/GassistPi/src/indicator.py", line 51, in <module>
Oct 26 16:02:32 raspberrypi python[3405]:     GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
Oct 26 16:02:32 raspberrypi python[3405]: RuntimeError: Failed to add edge detection
Oct 26 16:02:32 raspberrypi systemd[1]: gassistpi-ok-google.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 16:02:32 raspberrypi systemd[1]: gassistpi-ok-google.service: Unit entered failed state.
Oct 26 16:02:32 raspberrypi systemd[1]: gassistpi-ok-google.service: Failed with result 'exit-code'.
Oct 26 16:02:33 raspberrypi systemd[1]: gassistpi-ok-google.service: Service hold-off time over, scheduling restart.
Oct 26 16:02:33 raspberrypi systemd[1]: Stopped Google Assistant-Voice.
Oct 26 16:02:33 raspberrypi systemd[1]: Started Google Assistant-Voice.

```

It was already unstable yesterday, but I achieve to make it start after some reboots.

**Comment by shivasiddharth** [comment]
@saiedmethal , @ankurshah963 , @Kintounn  and @BriKKou  Are you people using October version of the Raspbian stretch ? Can you check that and get back ?

**Comment by BriKKou** [comment]
Yes ! Just made a french install a few days ago with the last strech version.

I just found this in another project: https://github.com/alexa-pi/AlexaPi/issues/199
With solution: https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#running-pa-in-system-wide-mode-recommended

May be that could help

**Comment by shivasiddharth** [comment]
@BriKKou  Can you post the /boot/config.txt ?

**Comment by BriKKou** [comment]
In **/etc/pulse/client.conf**, **autospawn** was already set to **no**, but I ran 
` sudo apt-get uninstall pulseaudio`

And know the error disapears, but after entering:

```
source env/bin/activate
pip uninstall RPi.GPIO
pip install RPi.GPIO==0.6.3
```

and rebooting, it still won't boot and new error apears (vlcpulse + PulsAudio, I didn't copy the error sorry).

I then rebooted twice and know, it seems to work.
The only error I can see in the log are linked to SSL

```
Oct 26 16:38:05 raspberrypi python[1202]: OpenSSL.SSL.Error: [('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')]
Oct 26 16:38:05 raspberrypi python[1202]: During handling of the above exception, another exception occurred:
Oct 26 16:38:05 raspberrypi python[1202]: Traceback (most recent call last):
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Oct 26 16:38:05 raspberrypi python[1202]:     chunked=chunked)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 343, in _make_request
Oct 26 16:38:05 raspberrypi python[1202]:     self._validate_conn(conn)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
Oct 26 16:38:05 raspberrypi python[1202]:     conn.connect()
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/connection.py", line 344, in connect
Oct 26 16:38:05 raspberrypi python[1202]:     ssl_context=context)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 342, in ssl_wrap_socket
Oct 26 16:38:05 raspberrypi python[1202]:     return context.wrap_socket(sock, server_hostname=server_hostname)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
Oct 26 16:38:05 raspberrypi python[1202]:     raise ssl.SSLError('bad handshake: %r' % e)
Oct 26 16:38:05 raspberrypi python[1202]: ssl.SSLError: ("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)
Oct 26 16:38:05 raspberrypi python[1202]: During handling of the above exception, another exception occurred:
Oct 26 16:38:05 raspberrypi python[1202]: Traceback (most recent call last):
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
Oct 26 16:38:05 raspberrypi python[1202]:     timeout=timeout
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Oct 26 16:38:05 raspberrypi python[1202]:     _stacktrace=sys.exc_info()[2])
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
Oct 26 16:38:05 raspberrypi python[1202]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Oct 26 16:38:05 raspberrypi python[1202]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLError("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",),))
Oct 26 16:38:05 raspberrypi python[1202]: During handling of the above exception, another exception occurred:
Oct 26 16:38:05 raspberrypi python[1202]: Traceback (most recent call last):
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/GassistPi/src/main.py", line 40, in <module>
Oct 26 16:38:05 raspberrypi python[1202]:     from actions import say
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/GassistPi/src/actions.py", line 15, in <module>
Oct 26 16:38:05 raspberrypi python[1202]:     from mediaplayer import api
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/GassistPi/src/mediaplayer.py", line 21, in <module>
Oct 26 16:38:05 raspberrypi python[1202]:     logged_in = api.login(configuration['Gmusicapi']['email'],configuration['Gmusicapi']['password'] , configuration['Gmusicapi']['deviceid'])
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/clients/mobileclient.py", line 147, in login
Oct 26 16:38:05 raspberrypi python[1202]:     if not self.session.login(email, password, device_id):
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/gmusicapi/session.py", line 191, in login
Oct 26 16:38:05 raspberrypi python[1202]:     res = gpsoauth.perform_master_login(email, password, android_id)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/gpsoauth/__init__.py", line 70, in perform_master_login
Oct 26 16:38:05 raspberrypi python[1202]:     return _perform_auth_request(data, proxy)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/gpsoauth/__init__.py", line 26, in _perform_auth_request
Oct 26 16:38:05 raspberrypi python[1202]:     headers={'User-Agent': useragent})
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/requests/sessions.py", line 572, in post
Oct 26 16:38:05 raspberrypi python[1202]:     return self.request('POST', url, data=data, json=json, **kwargs)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/requests/sessions.py", line 524, in request
Oct 26 16:38:05 raspberrypi python[1202]:     resp = self.send(prep, **send_kwargs)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/requests/sessions.py", line 637, in send
Oct 26 16:38:05 raspberrypi python[1202]:     r = adapter.send(request, **kwargs)
Oct 26 16:38:05 raspberrypi python[1202]:   File "/home/pi/env/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
Oct 26 16:38:05 raspberrypi python[1202]:     raise SSLError(e, request=request)
Oct 26 16:38:05 raspberrypi python[1202]: requests.exceptions.SSLError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLError("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",),))
Oct 26 16:38:06 raspberrypi systemd[1]: gassistpi-ok-google.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 16:38:06 raspberrypi systemd[1]: gassistpi-ok-google.service: Unit entered failed state.
Oct 26 16:38:06 raspberrypi systemd[1]: gassistpi-ok-google.service: Failed with result 'exit-code'.
Oct 26 16:38:06 raspberrypi systemd[1]: gassistpi-ok-google.service: Service hold-off time over, scheduling restart.
Oct 26 16:38:06 raspberrypi systemd[1]: Stopped Google Assistant-Voice.
Oct 26 16:38:06 raspberrypi systemd[1]: Started Google Assistant-Voice.

```

**Comment by BriKKou** [comment]
Actually, I posted the answer to quickly.

```
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:version: 11.0.3
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:initialized
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:logged out
Oct 26 16:45:22 raspberrypi python[2275]: INFO:gmusicapi.Mobileclient1:failed to authenticate
Oct 26 16:45:22 raspberrypi python[2275]: [016297b8] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Oct 26 16:45:22 raspberrypi python[2275]: [016223e0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Oct 26 16:45:23 raspberrypi python[2275]: AIY-HAT
Oct 26 16:45:23 raspberrypi python[2275]: Initializing GPIO 25 for assistant activity indication
Oct 26 16:45:23 raspberrypi python[2275]: ERROR:__main__:number of hotwords in decoder_model (3) and sensitivity (2) does not match
Oct 26 16:45:23 raspberrypi python[2275]: Traceback (most recent call last):
Oct 26 16:45:23 raspberrypi python[2275]:   File "/home/pi/GassistPi/src/main.py", line 666, in <module>
Oct 26 16:45:23 raspberrypi python[2275]:     Myassistant().main()
Oct 26 16:45:23 raspberrypi python[2275]:   File "/home/pi/GassistPi/src/main.py", line 158, in __init__
Oct 26 16:45:23 raspberrypi python[2275]:     self.detector = snowboydecoder.HotwordDetector(models, sensitivity=self.sensitivity)
Oct 26 16:45:23 raspberrypi python[2275]:   File "/home/pi/GassistPi/src/snowboydecoder.py", line 100, in __init__
Oct 26 16:45:23 raspberrypi python[2275]:     "(%d) does not match" % (self.num_hotwords, len(sensitivity))
Oct 26 16:45:23 raspberrypi python[2275]: AssertionError: number of hotwords in decoder_model (3) and sensitivity (2) does not match
Oct 26 16:45:24 raspberrypi systemd[1]: gassistpi-ok-google.service: Service hold-off time over, scheduling restart.
Oct 26 16:45:24 raspberrypi systemd[1]: Stopped Google Assistant-Voice.
Oct 26 16:45:24 raspberrypi systemd[1]: Started Google Assistant-Voice.
```

**Comment by ankurshah963** [comment]
I am using raspbian os latest version with latest updates assistant ( October).

<not change config. Yaml file.
<no any enable 1 wire pi interfacing.

**Comment by shivasiddharth** [comment]
@BriKKou  Your latets issue is with Gmusicapi's device id. This has already been discussed before. https://github.com/shivasiddharth/GassistPi/issues/363#issuecomment-392613507

**Comment by BriKKou** [comment]
> @BriKKou Can you post the /boot/config.txt ?

```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
#dtparam=audio=on
dtoverlay=i2s-mmap
dtoverlay=googlevoicehat-soundcard
dtparam=spi=on
dtparam=i2c_arm=on
dtoverlay=w1-gpio
```

**Comment by ankurshah963** [comment]
I am using raspbian os latest version with latest updates assistant ( October).

<not change config. Yaml file.
<no any enable 1 wire pi interfacing.

**Comment by shivasiddharth** [comment]
@BriKKou  Are you using Jarvis model ? This issue has already been discussed https://github.com/shivasiddharth/GassistPi/issues/455#issuecomment-408195168

**Comment by shivasiddharth** [comment]
@ankurshah963 , @saiedmethal  @Kintounn 
Try the following.

```
source env/bin/activate
pip uninstall RPi.GPIO
pip install RPi.GPIO==0.6.3
```

**Comment by BriKKou** [comment]
Thanks @shivasiddharth you're THE man.
I had many issues and you figures them all!

**Comment by ankurshah963** [comment]
> @ankurshah963 , @saiedmethal @Kintounn
> Try the following.
> 
> ```
> source env/bin/activate
> pip uninstall RPi.GPIO
> pip install RPi.GPIO==0.6.3
> ```

dear sir i will try this but not response assistance.
 manually start 
some of error are create

INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 11.0.3
INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:gmusicapi.Mobileclient1:failed to authenticate
[030a9450] pulse audio output error: PulseAudio server connection failure: Connection refused
[0309a1d8] pulse audio output error: PulseAudio server connection failure: Connection refused
USB-MIC-JACK
Initializing GPIOs 5 and 6 for assistant activity indication
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
device_model_id: new-gassistpi-2aru4o
device_id: 0D2CER1BF6AA536744D440003B7AVCDD0

ON_MUTED_CHANGED:
  {"is_muted": true}
ON_MUTED_CHANGED:
  {"is_muted": true}
ON_START_FINISHED
ON_START_FINISHED
ON_MUTED_CHANGED:
  {"is_muted": true}
ON_MUTED_CHANGED:
  {"is_muted": true}

not response.

**Comment by nirmalkumarv** [comment]
@ankurshah963, Were you able to resolve this issue. I am getting the exact error. USB Mic not recognized by Gassist. I have tested the mic separately by using arecord and it works.

**Comment by pmishev** [comment]
I managed to resolve this error:
```
Nov 24 11:44:52 frame pulseaudio[3255]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Nov 24 11:44:52 frame pulseaudio[3255]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```
by editing `/lib/systemd/system/gassistpi-ok-google.service` and adding this line:
```
[Service]
Environment=DISPLAY=:0
```

as seen here: https://github.com/google/aiyprojects-raspbian/issues/403#issuecomment-396355680
