### ISSUE TITLE
Change language GassistPi

### ISSUE THREAD

**Issue by pernordeman** [shivasiddharth/GassistPi#541]
Hello!

trying to change the Gassist to swedish, hence the google assistant have been declared in sweden.
Tried to just change the settings in action.py file but it does not work, thinking it could be something more to it. Do a need to change all the "call signs" to get it working or is it something else?

Great project! 
Best regards

**Comment by aro28** [comment]
Language | Language-Region | Language (English name)
-- | -- | --
Deutsch (Deutschland) | de-DE | German (Germany)
English (Australia) | en-AU | English (Australia)
English (Canada) | en-CA | English (Canada)
English (Great Britain) | en-GB | English (United Kingdom)
English (United States) | en-US | English (United States)
Français (Canada) | fr-CA | French (Canada)
Français (France) | fr-FR | French (France)
Italiano (Italia) | it-IT | Italian (Italy)
日本語（日本） | ja-JP | Japanese (Japan)

**Comment by shivasiddharth** [comment]
Changing language in actions.py does not affect the Assistant's language, it only changes/alters the system generated speech.  Google has not released support for Swedish.
