### ISSUE TITLE
Assistant freezes on Deezer request

### ISSUE THREAD

**Issue by matrix98053** [shivasiddharth/GassistPi#554]
### Describe the bug:
```
If i ask GAssistant to play playlist 1 from Deezer my Assistant hangs/freezes/exits
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
yes

### 2. Is the issue related to assistant installation ?
No

### Paste the contents of the terminal below
```

ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "open playlist one from Deezer"}
stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR:__main__:'data'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 662, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 654, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1480, in deezer_playlist_select
    if deezer_user_playlist_info['data'] != []:
KeyError: 'data'


```

**Comment by shivasiddharth** [comment]
Can you confirm that you have entered the Deezer userid correctly in the config.yaml file. it should be a number within quotes.

**Comment by matrix98053** [comment]
Hi, yes. I have entered it correct and double checked it to be correct within the quotes.

**Comment by matrix98053** [comment]
If i am not mistaken it should tell me if it cannot play the playlist or cannot find the name specified? I get no response and have to manually start the assistant again afterwards...

**Comment by shivasiddharth** [comment]
Open the actions.py and after this line https://github.com/shivasiddharth/GassistPi/blob/ada7dbad01b8252f759da59e13a4a50aa284b664/src/actions.py#L1479
Enter
`print(deezer_user_playlist_info)`
Now manually run the assistant and paste here the contents of the terminal.

**Comment by matrix98053** [comment]
{"text": "play playlist 1 from Deezer"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist 1 from Deezer"}
stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR:__main__:name 'deezer__user_playlist_info' is not defined
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 662, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 654, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1480, in deezer_playlist_select
    print(deezer__user_playlist_info)
NameError: name 'deezer__user_playlist_info' is not defined

**Comment by matrix98053** [comment]
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist 1 on Deezer"}
stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{'total': 0, 'checksum': 'b0308b5378709824948ad7e2e659e33b40cd750bba9870f18aada2478b24840a', 'data': []}
ERROR:__main__:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 662, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 654, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1485, in deezer_playlist_select
    say("No playlists found for the user")
  File "/home/pi/GassistPi/src/actions.py", line 209, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by shivasiddharth** [comment]
check #534  for the above mentioned error
