### ISSUE TITLE
Update for AIY kit

### ISSUE THREAD

**Issue by schubb2003** [shivasiddharth/GassistPi#56]
Hello,
Enhancement/update request now that the AIY kit is out en masse you may wish to add a note that GPIO 05/06 need replaced in main.py with 25.

This is minor, but your build is still better than the kit and I would like to see yours kept up even with the kit coming as an all in one.

maybe toss in a line "if you are using the AIY kit, to get the button LED working you need to update the GPIO settings from 05/06 to 25."
sed -i 's/05/25/g' main.py
sed -i 's/06/25/g' main.py

**Comment by shivasiddharth** [comment]
I will update the project with AIY like blink indicator on GPIO25 over this weekend. And sometime later, the push-button on GPIO23 as a mute button.

**Comment by shivasiddharth** [comment]
Ok, i have update the project with AIY like indicator on GPIO 25. Feel free to test it. Please refer to the GPIO table in readme for the new GPIO allocation.
I am closing this issue, you can reopen it if necessary.
