### ISSUE TITLE
Multiple gassitpi in the same piece

### ISSUE THREAD

**Issue by bimbim2401** [shivasiddharth/GassistPi#566]
When I launch multiple raspberry with gassitpi, they all respond. Do you think it can be possible to manage the question only by one gassitpi?

**Comment by shivasiddharth** [comment]
I have added mute buton. You need to mute the others that you are not using. Please use gitter for general queries.

**Comment by bimbim2401** [comment]
I do not ask for a mute button 

All the gassistpi are available but only one respond

**Comment by shivasiddharth** [comment]
When ever two or more assistants are triggered simultaneously only one will respond. That is how google assistant works. If that is what you meant.

**Comment by bimbim2401** [comment]
Thanks but I know how google assistant work but gassitpi do not do the same. All my gassistpi respond and not exactly in the same time this is my problem. I want the same comportement like google home

**Comment by shivasiddharth** [comment]
They will not respond at the same time..

**Comment by bimbim2401** [comment]
I want only one to respond and the problem is not all à the same time or not a the same time.
