### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by MIcenter** [shivasiddharth/GassistPi#572]
### Describe the bug:
error while executing sudo  ./GassistPi/scripts/gassist-installer-pi3.sh  

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes
### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

pi@raspberrypi:~ $ sudo  ./GassistPi/scripts/gassist-installer-pi3.sh  
This script must run as pi, trying to change user...

Enter the your full credential file name including the path and .json extension: /home/pi/client_secret_1019726733453-jr3j3u1ml1dnlje9t046agkopq7ca8bc.apps.googleusercontent.com.json

Enter the your Google Cloud Console Project-Id: gassistpi-7c4ad

Enter the modelid that was generated in the actions console: gassistpi-7c4ad-gassistpi-4tu8lc

Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]     
Fetched 40.3 kB in 3s (12.6 kB/s)                          
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2+rpt2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjack-jackd2-dev is already the newest version (1.9.10+20150825git1ed50c92~dfsg-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3+deb9u2).
portaudio19-dev is already the newest version (19.6.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pyaudio in /usr/local/lib/python2.7/dist-packages
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libatlas-base-dev is already the newest version (3.10.3-1+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
E: Unable to locate package astral=
E: Unable to locate package ws4py=
E: Unable to locate package requests=
pi@raspberrypi:~ $

**Comment by shivasiddharth** [comment]
Fixed the issue in previous commit.
