### ISSUE TITLE
The headless auto start doesn't work and I can't manually start the assistant. 

### ISSUE THREAD

**Issue by Kintounn** [shivasiddharth/GassistPi#598]
### Describe the bug:

The headless auto start doesn't work and I can't manually start the assistant. 

/home/${USER}/env/bin/python -u /home/${USER}/GassistPi/src/main.py --device_model_id xxxxxxxx

INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 11.0.3
INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:gmusicapi.Mobileclient1:failed to authenticate
[02fe11f0] pulse audio output error: PulseAudio server connection failure: Connection refused
[03021b68] pulse audio output error: PulseAudio server connection failure: Connection refused
USB-MIC-JACK
Traceback (most recent call last):
File "/home/pi/GassistPi/src/main.py", line 64, in 
from indicator import assistantindicator
File "/home/pi/GassistPi/src/indicator.py", line 51, in 
GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
RuntimeError: Failed to add edge detection
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
No

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 11.0.3
INFO:gmusicapi.Mobileclient1:logging to: /home/pi/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:gmusicapi.Mobileclient1:failed to authenticate
[02fe11f0] pulse audio output error: PulseAudio server connection failure: Connection refused
[03021b68] pulse audio output error: PulseAudio server connection failure: Connection refused
USB-MIC-JACK
Traceback (most recent call last):
File "/home/pi/GassistPi/src/main.py", line 64, in 
from indicator import assistantindicator
File "/home/pi/GassistPi/src/indicator.py", line 51, in 
GPIO.add_event_detect(stoppushbutton,GPIO.FALLING)
RuntimeError: Failed to add edge detection
### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
As people have already reported this in #540 , i will deal with this there.
