### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by dudukk1312** [shivasiddharth/GassistPi#60]
Hi,

I tried to run snowboy.py by `sudo python -u Doo_home/GassistPi/src/snowboy.py` but it told me that missing module named "click" in assistant.py. How to take this module?
And when I run with `python3 -m snowboy`
It raise these error:

> `Traceback (most recent call last):
>   File "/home/pi/Doo_home/GassistPi/src/snowboydetect.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
>   File "<frozen importlib._bootstrap>", line 1715, in load_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
> ImportError: dynamic module does not define init function (PyInit__snowboydetect)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/pi/Doo_home/GassistPi/src/snowboy.py", line 1, in <module>
>     import snowboydecoder
>   File "/home/pi/Doo_home/GassistPi/src/snowboydecoder.py", line 5, in <module>
>     import snowboydetect
>   File "/home/pi/Doo_home/GassistPi/src/snowboydetect.py", line 21, in <module>
>     _snowboydetect = swig_import_helper()
>   File "/home/pi/Doo_home/GassistPi/src/snowboydetect.py", line 20, in swig_import_helper
>     return importlib.import_module('_snowboydetect')
>   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: dynamic module does not define init function (PyInit__snowboydetect)`

Thank you

**Comment by shivasiddharth** [comment]
The issue has already been addressed in YouTube.  I have successfully updated the project to Python3. 
Cheers !
