### ISSUE TITLE
Question: How integration kodi works

### ISSUE THREAD

**Issue by davjimvar** [shivasiddharth/GassistPi#604]
Hello,
I read that GassistPi has Kodi integration without IFTTT. I would like to know how this integration works to do something similar with Plex, and then, of course, do PR.

I know IFTTT and custom-actions [more info]((https://developers.google.com/assistant/sdk/guides/library/python/extend/custom-actions) but I think you don't use these techniques.

Thanks for all

**Comment by shivasiddharth** [comment]
How the feature works ? Please go through README.
