### ISSUE TITLE
Use of __USER__ in GassistPi/systemd/gassistpi-ok-google.service

### ISSUE THREAD

**Issue by cnoorman** [shivasiddharth/GassistPi#607]
When installing the `gassistpi-ok-google.service` the variable `__USER__` is not translated (into pi). Consequently this service doesn't start.
Am I doing something wrong or should `__USER__` be replaced everywhere by `${USER}`  ??

**Comment by cnoorman** [comment]
Same story for `Assistants-Pi/systemd/alexa.service` in the Assistants-Pi installation script.

**Comment by shivasiddharth** [comment]
Issue seems to be isolated one. Its works for me and no one has reported issues with the service so far. Will leave the issue open to see if someone else reports the same thing.

**Comment by cnoorman** [comment]
It's fine with me. I worked around it, but I cannot find any use of leading and trailing underscores in a bash script (only in Python). And you see a second example of the problem in the reference above.

**Comment by cnoorman** [comment]
I changed `__USER__` to `%u`, but that translates into `root`.

**Comment by shivasiddharth** [comment]
I tried the scripts in ubuntu and __USER__ got translated to the user name. I have changed __USER__ to ${USER} in master. can you check if it solved the issue?

**Comment by cnoorman** [comment]
Unfortunately this does not solve the issue. $(USER) is not translated either. I understand what you want to accomplish, but pending the finale solution I suggest that you replace this just with `pi` in all `.service` files. At least that will work for 90% of the users.
