### ISSUE TITLE
Issue with google assistant authentication link

### ISSUE THREAD

**Issue by shaltut** [shivasiddharth/GassistPi#614]
when applying the command sudo  ./GassistPi/scripts/gassist-installer-pi3.sh on PI 3 i got alot of red errors in the tarminal  
![9fc3ae85-54f8-4cc0-9e5a-7abebc2446b0](https://user-images.githubusercontent.com/37026364/47969813-8fa49400-e085-11e8-9eb4-829d8bf172ff.jpg)

**Comment by shivasiddharth** [comment]
This is an issue with your network. Either your Internet is too slow or network got reset.
