### ISSUE TITLE
Need help with connecting a relay and control it

### ISSUE THREAD

**Issue by shaltut** [shivasiddharth/GassistPi#623]
### Describe the bug:
```
the assistant is now on and responding but i need a quick tutorial about how to control a relay with voice command because the video tutorial on the channel is outdated
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Use gitter for general queries. This place is only for issues.
