### ISSUE TITLE
Failed to auto start or manually start due to Hue error 

### ISSUE THREAD

**Issue by saiedmethal** [shivasiddharth/GassistPi#627]
### Describe the bug:
```
Failed to auto start or manually start due to Hue error, fresh installation after running  installer Executable  
i get an error of missing diyHue.service in systemd , after adding it manually the auto start keeps restarting / manual start gives the below errors 

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MUTED_CHANGED:
  {"is_muted": false}
ERROR:__main__:[Errno 2] No such file or directory: '/opt/hue-emulator/config.json'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 672, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 448, in main
    with open('/opt/hue-emulator/config.json', 'r') as config:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hue-emulator/config.json'

```

**Comment by shivasiddharth** [comment]
Replace you existing main.py with the updated script from master
