### ISSUE TITLE
install stops, missing diyhue.service

### ISSUE THREAD

**Issue by stnorheim** [shivasiddharth/GassistPi#631]
### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```
0 oppgraderte, 0 nylig installerte, 0 å fjerne og 38 ikke oppgradert.
sed: kan ikke lese /home/pi/GassistPi/systemd/diyHue.service: Ingen slik fil eller filkatalog

seems that the installation cannot compleat due to its missing diyhue.service
```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
Just fixed it in the last commit. Delete the existing GassistPi folder and clone the git again.
