### ISSUE TITLE
[RPi0][pushbutton.py] VLC volume is saved only when VLC is playing

### ISSUE THREAD

**Issue by Darmur** [shivasiddharth/GassistPi#647]
### Describe the bug:
```
I have my Assistant based on RPi0 with two powerful speakers. If I put the music volume at 100%, the two microphones are saturated and the trigger "snowboy" is not recognized anymore... basically I can't lower the volume. If I press the button to stop music, I can't save a different music volume for next playback, because the file .mediavolume.json is updated only when VLC is playing. The only way is to SSH and manually edit that file.

Some modification can be done to the pushbutton.py code (and to main.py as well) to be able to save the .mediavolume.json file even if VLC is not playing

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment]
This is associated with #597 Both are interlinked. Will close this.. Monitor the progress in #597
