### ISSUE TITLE
Shuffle my music on Kodi doesn't work

### ISSUE THREAD

**Issue by pmishev** [shivasiddharth/GassistPi#656]
```
Nov 27 23:14:45 frame python3[10155]: ON_RECOGNIZING_SPEECH_FINISHED:
Nov 27 23:14:45 frame python3[10155]:   {"text": "shuffle my music on kodi"}
Nov 27 23:14:46 frame python3[10155]: ERROR:__main__:'result'
Nov 27 23:14:46 frame python3[10155]: Traceback (most recent call last):
Nov 27 23:14:46 frame python3[10155]:   File "/home/pi/GassistPi/src/main.py", line 693, in <module>
Nov 27 23:14:46 frame python3[10155]:     Myassistant().main()
Nov 27 23:14:46 frame python3[10155]:   File "/home/pi/GassistPi/src/main.py", line 567, in main
Nov 27 23:14:46 frame python3[10155]:     kodiactions(str(usrcmd).lower())
Nov 27 23:14:46 frame python3[10155]:   File "/home/pi/GassistPi/src/actions.py", line 703, in kodiactions
Nov 27 23:14:46 frame python3[10155]:     shufflekodi()
Nov 27 23:14:46 frame python3[10155]:   File "/home/pi/GassistPi/src/actions.py", line 647, in shufflekodi
Nov 27 23:14:46 frame python3[10155]:     numfiles=len(files["result"]["files"])
Nov 27 23:14:46 frame python3[10155]: KeyError: 'result'
```

I added a `pprint(files)` before that line and I get:
```
Nov 27 23:19:21 frame python3[11009]: {'error': {'code': -32602, 'message': 'Invalid params.'},
Nov 27 23:19:21 frame python3[11009]:  'id': 1,
Nov 27 23:19:21 frame python3[11009]:  'jsonrpc': '2.0'}
```

As a side note, as with any other error I've encountered so far, after the error the assistant no longer works until service is restarted. I don't know anything about Python, but is there no way to globally try..catch any such errors, so at least it doesn't crash when there's an error?

**Comment by shivasiddharth** [comment]
Can you add a `print(files)` command after the line `files=kodi.Files.GetDirectory({"directory": musicdirectory, "media": "music"})`

**Comment by pmishev** [comment]
uhm, that's what I did above, but here it is again:
```
 {'error': {'message': 'Invalid params.', 'code': -32602}, 'id': 1, 'jsonrpc': '2.0'}
```

I also added a `print(musicdirectory)` that shows `/home/osmc/Music/`, which is a valid path on the kodi server.

**Comment by shivasiddharth** [comment]
What Kodi are you running ? Is the Kodi and Assistant Running on same Pi ?

**Comment by pmishev** [comment]
I'm running the latest OSMC (Kodi 17.6) on another RPi on the local network

**Comment by shivasiddharth** [comment]
Can you check if the music files have been placed in the music directory and added to the library. If the folder has not been added to the library, you will get this error. Also, the music folder should contain only songs and mixing video files with music sometimes returns this error.

**Comment by pmishev** [comment]
Thanks for the tip! `/home/osmc/Music/` is actually a symlink, so I tried with the actual folder this time and it's working... kind of...
It took 7 minutes from showing the list of files until it actually started playing. I have ~30GB of music, so it's probably adding everything file-by-file, which is not very practical. Is there anything that can be done for that in your code or is this an issue with Kodi?

**Comment by shivasiddharth** [comment]
The list and details are obtained on the fly, thats why its taking time. Other way around is to locally build a database for the assistant to access. But that comes with its own set of disadvantages. To mirror any changes that you make to the kodi files list, local database has to be synced. If you fail to sync, the assistant will crash again. 
The ideal option will be to run OSMC and Assistant on same pi. With the last update, that should be possible by just adding the raspbian link to the sources list. SSH into the OSMC, run the following and paste the op here.
`sudo nano /etc/apt/sources.list`

**Comment by pmishev** [comment]
Unfortunately, it's not an option for me to install osmc and the assistant on the same rpi.
Is it possible instead to play a predefined playlist? like:

Play **Party mode** playlist on Kodi

This way, it shouldn't be necessary to enumerate all files - only a few playlists and Kodi will take care of the shuffling itself?

**Comment by shivasiddharth** [comment]
I shall add an enhancement tag then. Will look into it.

**Comment by shivasiddharth** [comment]
This has been fixed.
