### ISSUE TITLE
NameError: name 'Translator' is not defined

### ISSUE THREAD

**Issue by Casuallynoted** [shivasiddharth/GassistPi#658]
Getting this crash when I try to run manually:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 44, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 191, in <module>
    translator = Translator()
NameError: name 'Translator' is not defined

**Comment by Casuallynoted** [comment]
Oh gosh, I’m sorry. Didn’t mean to go off-template. Google Assistant doesn’t seem to launch after showing this error however.

**Comment by shivasiddharth** [comment]
I have fixed the error in the master. Open your actions.py file and delete the line
 translator = Translator()
Save and restart the assistant. It should work normally

**Comment by IngmarG** [comment]
Lol, was just about to report the same. Correcting and testing.
