### ISSUE TITLE
Deactivate spotify

### ISSUE THREAD

**Issue by DewGew** [shivasiddharth/GassistPi#663]
How can I deactivate custom Spotify function?
I have Spotify already connected in my Google home app.
I got Spotify play on my chromecast device but then my rpi says ”no music Links” and hangs.. i dont use the Spotify on the rpi

**Comment by IngmarG** [comment]
From main.py, delete (or comment) the occurences of spotify (64, 673-676).

Haven't tested that, but it's kind of obvious

**Comment by DewGew** [comment]
Thanks @IngmarG To deactivate functions I dont need and I dont want them to mess up things I have to change those in main.py? Or do I have to change any More files?

**Comment by shivasiddharth** [comment]
Its just main.py. In the next update i will add switches in config.yaml for all the custom functions.

**Comment by DewGew** [comment]
Great thanks..

**Comment by shivasiddharth** [comment]
@DewGew , Replace your existing main.py and config.yaml with the files from this branch https://github.com/shivasiddharth/GassistPi/tree/custom-actions-switch  and check if the switch control works. You turn on or off the customs by setting the control to 'Enabled' or 'Disabled'.

**Comment by IngmarG** [comment]
Haven't tested it, but this is great.

**Comment by DewGew** [comment]
Seems to work..
But I think you have a 2 switches on kodi:
`Kodi:
  Kodi_Control: 'Enabled'
  control: 'Disabled'`

**Comment by shivasiddharth** [comment]
I have fixed that now.

**Comment by DewGew** [comment]
This works great.. 👍  merge this to master.
