### ISSUE TITLE
How to re run the installer?

### ISSUE THREAD

**Issue by Mark-papi** [shivasiddharth/GassistPi#683]
How to re run the installer so to be updated,  without loosing all the files (essential files) that I have most importantly the assistant model from Google ( because it took me like days to do it) ?

**Comment by shivasiddharth** [comment]
This is not how Git's issue works my friend (at least for this project). I have created a chat room (gitter) specifically for this kind of purpose (link is in the README). You do not post non-issue queries here.

Re-running the installer does not mean generating new model-ids. You can use your old model ids, but the project's file structure has changed with some newer python packages. Even the service file names have changed, so its basically like following the README all over.
