### ISSUE TITLE
Mic off, 'ok google' doesnt pick up however custom wake still works

### ISSUE THREAD

**Issue by enduser001** [shivasiddharth/GassistPi#684]
I have a GassistPi working with a custom wake word (my son's name) and 'ok google.' - hooray!

However, if I push the button to turn off mic, 'ok google' doesn't respond (expected behavior) however the custom wake word continues to work (unexpected behavior).

Other than that, I get a kick outta seeing if my 6 yr old can do simple math before Google can respond.

**Comment by shivasiddharth** [comment]
This has already been discussed in Gitter and some other issue (i dont remember the number). This is intentional, i have set the mute function only for Ok-Google and not the custom wakeword.
