### ISSUE TITLE
Installing gassistPI on windows 

### ISSUE THREAD

**Issue by bimbim2401** [shivasiddharth/GassistPi#689]
Hello
i have follow your video tutorial with virtualbox and Ubuntu LTS but i have this error from your installer 

You are advised to use the stretch version of the OS
exitting the installer

Is you tutorial is always ok with the last version of Gassistpi installer ?

**Comment by shivasiddharth** [comment]
You have used the wrong branch. Do not use master, use the windows desktop branch.
