### ISSUE TITLE
Google Assistant says, "actually there is some basic settings, that need your permission." 

### ISSUE THREAD

**Issue by nianik5098** [shivasiddharth/GassistPi#69]
I replicated the full project on raspi 3b with python3. now whenever i ask a general question the google assistant replies with 'actually there is some basic settings, that need your permission.'

should i edit main.py or actions.py with anything?

**Comment by shivasiddharth** [comment]
Please read through this https://developers.google.com/assistant/sdk/develop/python/config-dev-project-and-account There is a section called "**Set activity controls for your account**"
