### ISSUE TITLE
Gassistpi control from Android phone 

### ISSUE THREAD

**Issue by reydecopas** [shivasiddharth/GassistPi#698]
Hi, 
I have installed Gassistpi in the same SBC with domoticz
Is it possible to control gassistpi but instead of control through the mic and the speaker... control it far away from an Android phone  with 'ok google'?

Sorry if this is not the right place for asking this kind of questions.

Great project!!!! Congrats!!!!

**Comment by aandroide** [comment]
I stay tuned also interests me

**Comment by shivasiddharth** [comment]
Closed using #703

**Comment by aandroide** [comment]
it's not really what the user asked, in my opinion.
definitely intended to make the phone assistant interact with the assistant on the raspberry by saying words that trigger the assistant even remotely.
Surely you can also do with mqtt, just be a little 'practical in developing a custom application on the phone that integrates the voice and send the strings to mqtt on the raspberry

**Comment by shivasiddharth** [comment]
Frankly, I missed the part in the query with "ok google". But in the MQTT Dash app, users can create switch tiles that sends MQTT commands.

**Comment by shivasiddharth** [comment]
@aandroide ,  You do not need a custom application. I have explained as to how it can be achieved in #703.

**Comment by shivasiddharth** [comment]
@aandroide  Chekout this commit https://github.com/shivasiddharth/GassistPi/commit/ba899e9edbcc5835df3d4a95045484b7ae8c776b
