### ISSUE TITLE
Probably a stupid question but does this stay updated on my pi as you add amazing new functions.

### ISSUE THREAD

**Issue by jcksnmdy** [shivasiddharth/GassistPi#712]
Probably a stupid question but does this stay updated on my pi as you add amazing new features?

**Comment by shivasiddharth** [comment]
If the update is a SDK bump you need to re run the installer, otherwise you can use this script .https://github.com/shivasiddharth/GassistPi/blob/update-script/GassistPi-Update-Script.sh

**Comment by DewGew** [comment]
Do you comment if its a sdk update in the readme file?
