### ISSUE TITLE
google asistant error dynamic module

### ISSUE THREAD

**Issue by bazlama** [shivasiddharth/GassistPi#718]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Paste your Board and OS details here.   
```

### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

### If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```
python -u /home/bazoka/GassistPi/src/main.py --device_model_id 'asistan-ubuntu-gassistpi-vck9ls'
Traceback (most recent call last):
  File "/home/bazoka/GassistPi/src/main.py", line 29, in <module>
    import snowboydecoder
  File "/home/bazoka/GassistPi/src/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/bazoka/GassistPi/src/snowboydetect.py", line 18, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/bazoka/GassistPi/src/snowboydetect.py", line 17, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (init_snowboydetect)

```

**Comment by shivasiddharth** [comment]
Closing the issue for failing to provide the requested details in the template.
