### ISSUE TITLE
USB Mic + AIY Hat Speaker audio config file help

### ISSUE THREAD

**Issue by patricktelling** [shivasiddharth/GassistPi#72]
Hello. I am trying to set up snowboy.py to use a **USB mic** with the **AIY-Hat speaker**, but am having trouble creating the right **asound.conf** file. Could you provide one in a future update?

> This is what I tried using but it didn't work:
```
options snd_rpi_googlemihat_soundcard index=0

pcm.softvol {
    type softvol
    slave.pcm dmix
    control {
        name Master
        card 0
    }
}


pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}

pcm.!default {
        type asym
	playback.pcm "plug:softvol"
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}

ctl.!default {
    type hw
    card 0
}
```

**Comment by shivasiddharth** [comment]
I have covered all the possible audio config setups. This can be used for every other case. In your case, the card id for mic 1 and card id for speaker is 0. So you can use the audio config that i have given for USB mic and Onboard Jack..
