### ISSUE TITLE
Gassistpi log file not present

### ISSUE THREAD

**Issue by bimbim2401** [shivasiddharth/GassistPi#721]
Hello

Just a stupid question but I have follow your tuto for installing gassistpi on virtualbox, everything is ok but I cannot succeed to have the gassistpi log file in the tmp folder 

For information, in order to have the led ring works with Windows and an arduino I made a python script which read the state of the assistant in the log file 

Thanks for your response

**Comment by shivasiddharth** [comment]
Duplicate of #544
