### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by DewGew** [shivasiddharth/GassistPi#723]
I Need to send a mqtt message somewhere in main.py or actions.py to my domoticz PI to change a selector switch when I start my radio. I have mqtt broker already configured and set mqtt credentials in config.yaml.

sending switch command to domoticz:
`{"command": "switchlight", "idx": 123, "switchcmd": "Set Level", "level": 10 }`

topic:
`domoticz/in`

How can I manage to do this?

**Comment by shivasiddharth** [comment]
In the main.py i have already defined the client. Convert the json to string using json.dumps. then use client.publish(mqtt topic, mqtt message).

Please use gitter for non-issue stuff.

**Comment by NGOLOC37** [comment]
I use client.publish but got error. Can u help me. Thanks!
![image](https://user-images.githubusercontent.com/45537098/183453212-2b97a298-33d7-4134-8f65-85387c19f6f6.png)
