### ISSUE TITLE
Home Assistant Compatible?

### ISSUE THREAD

**Issue by helloworld2k** [shivasiddharth/GassistPi#74]
Hi Shiva,

Thanks for upgrading the project to the Python 3.
I currently use Home Assistant which is open source automation platform on Raspberry Pi, Google Assistant is one of the add-on, may I know is there any way I can put the GassistPi to this platform? I quite like your project rather than the original, thank you.

Regards,
Jun

**Comment by shivasiddharth** [comment]
You need to modify the "pi" user accounts mentioned in this code to make it work in Home assistant. In the next update, i will try and include home assistant with the google assistant.

**Comment by Electronlibre2012** [comment]
> 
> 
> Hi Shiva,
> 
> Thanks for upgrading the project to the Python 3.
> I currently use Home Assistant which is open source automation platform on Raspberry Pi, Google Assistant is one of the add-on, may I know is there any way I can put the GassistPi to this platform? I quite like your project rather than the original, thank you.
> 
> Regards,
> Jun

Hello @helloworld2k ,

very interested to add the Gassistpi to a media_player entity in HA!! Have you succeed in to see it in HA please?

Thanks
