### ISSUE TITLE
The volume gets low after playing audio from Youtube or Ganna.com

### ISSUE THREAD

**Issue by yash2197** [shivasiddharth/GassistPi#746]
The assistant switches volume low to be heard but keeps the volume low as it is which makes it mute for conversation

**Comment by shivasiddharth** [comment]
I am really unable to understand what your issue is.

**Comment by yash2197** [comment]
Okay here's a brief....
The pi boots up and the assistant is initialised
It takes all the commands and the response is also in normal sound level
Now when a command to play music from Youtube or Ganna.com is issued voice is heard 'Getting Youtube link'
The song plays
Now the speaker volume is zero
If any command issued after this,the assistant processes it but no sound is heard in response
After manually starting the assistant I found out that the system volume of pi goes down to zero after wakeword is heard but it keeps it to zero after that

**Comment by shivasiddharth** [comment]
Is there any reason for not using the issue template issue template ? Closing this issue for not using the issue template.

**Comment by yash2197** [comment]
Could you help me out here...
As I have to manually increase the volume of pi by logging in
Thanks

**Comment by shivasiddharth** [comment]
Unless someone has played around with the scripts, what you are saying will not happen. Nowhere in the script i have set the assistant to control or change the master/pi volume. The volume dipping is confined only to the vlc player.

**Comment by yash2197** [comment]
Could you specify where exactly that part is written in the code....
Would look at it and try to solve

**Comment by yash2197** [comment]
The volume dipping part

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi/blob/d4f25e6fca13180070948a2783f03f3e4fb96c0f/src/main.py#L308
