### ISSUE TITLE
Alarms and Timers

### ISSUE THREAD

**Issue by wangodanny** [shivasiddharth/GassistPi#75]
Hi
I like to have alarms and timers to be added as it means my pi can become a alarm clock which is important to me as a student. Thanks

**Comment by shivasiddharth** [comment]
Alarms and timers are inherent of SDK on ArmV7 Boards.

**Comment by wangodanny** [comment]
Hello, I was asking for this feature as o use a raspberry pi zero W and
like I said, this feature would help a lot.
