### ISSUE TITLE
Spotify issuse

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#755]
Here is my terminal output:

ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play wanna stay home from Spotify"}

stopping vlc
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: female-say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of female-say.mp3 finished.
wanna stay home
Segmentation fault

Please help!

**Comment by aandroide** [comment]
https://github.com/shivasiddharth/GassistPi/issues/753
