### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by Baidya99** [shivasiddharth/GassistPi#78]
I am using a usb sound card and analog mic. Even though I can use it without any driver on windows I am unable to use it on the pi.
Raspberry pi is is detecting the sound card but when testing the mic it it not being able to take input.
Could you please help.

**Comment by shivasiddharth** [comment]
Did you install the USB-DAC alsa configuration that i have given in the git ?

**Comment by Baidya99** [comment]
Yes I used that config

**Comment by shivasiddharth** [comment]
post the output of asoundrc and asound.conf !

**Comment by Baidya99** [comment]
asoundrc:

`pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}
pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:1,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
    }

    }
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "dmixer"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}
`

**Comment by Baidya99** [comment]
**asoundrc:**
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}
pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:1,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
    }

    }
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "dmixer"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}

**Comment by Baidya99** [comment]
**asound.conf:**
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}
pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:1,0"
        period_time 0
        period_size 1024
        buffer_size 8192
        rate 44100
    }

    }
pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "dmixer"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}

**Comment by Baidya99** [comment]
The speaker connected to usb sound card is working but the mic does not

**Comment by shivasiddharth** [comment]
Check your mic volume in alsamixer and also try removing `channels 1` from both asoundrc and asound.conf

**Comment by Baidya99** [comment]
Okay

**Comment by Baidya99** [comment]
Still not working.

**Comment by shivasiddharth** [comment]
Try recording an audio using arecord 
`arecord --device=hw:1,0 --format S16_LE --rate 44100 -c1 test.wav`
stop the recording  manually and playback the recorded audio.

**Comment by Baidya99** [comment]
how to playback?

**Comment by shivasiddharth** [comment]
aplay test.wav

**Comment by Baidya99** [comment]
okay

**Comment by Baidya99** [comment]
Getting error:
arecord: main:788: audio open error: Device or resource busy

**Comment by shivasiddharth** [comment]
I think the google assistant service is running which is making use of the mic. What do you mean by "Raspberry pi is is detecting the sound card but when testing the mic it it not being able to take input"? What exactly is your issue ?

**Comment by Baidya99** [comment]
The assistant service is not running because I have still not executed the command to make it autostart on boot and I had rebooted after carrying out the steps in Continuing after setting up audio.

**Comment by shivasiddharth** [comment]
then what do you mean by "when testing the mic it it not being able to take input"? how did you test it ?

**Comment by Baidya99** [comment]
By going to [https://www.onlinemictest.com/](https://www.onlinemictest.com/)
I did it before cloning your repository.

**Comment by shivasiddharth** [comment]
Before cloning my repository, you would not have had the audio config installed. USB-DACs in pi are not plug an play. Meaning, you need the alsa configs for mic to work. In pi and linux, you test mics with arecord. Use this command to record your mic and i am pretty much sure that it will work.
`arecord -d 10 -D hw:1,0 -r 16000 -f S16_LE -c1 /home/pi/mic-test.wav`
you need not stop the recording manually, it will automatically record samples only for 10 seconds. play the recorded samples using:
`aplay /home/pi/mic-test.wav`

**Comment by Baidya99** [comment]
Nope still the same error

**Comment by shivasiddharth** [comment]
Try this arecord with plugin !
`arecord -d 10 -D plughw:1,0 -r 16000 -f S16_LE -c1 /home/pi/mic-test.wav`

**Comment by Baidya99** [comment]
It is recording now but only noise is being recorded.

**Comment by shivasiddharth** [comment]
You need to look into your mic. I am closing this issue now.
