### ISSUE TITLE
Add device as a speaker to Google Home?

### ISSUE THREAD

**Issue by Tsury** [shivasiddharth/GassistPi#786]
This is not an issue, just a question.
Is it possible to add the Raspberry Pi as a Google Home speaker? All I want is to be able to see it listed as a speaker in Spotify, and direct the music there from my phone.

Thanks.

**Comment by aandroide** [comment]
no, it's not possible. google put this limit deliberately.

**Comment by Tsury** [comment]
@aandroide Thanks
