### ISSUE TITLE
Unable to Add Skills to Alexa Error The Language you selected doesn't match Alexa Account Settings

### ISSUE THREAD

**Issue by akishoreplanon** [shivasiddharth/GassistPi#81]
Hi Sid, 

I have selected the Language en-EU while configuring the Alexa. When i try to add the skill to my Alexa Pi from web/app. I see the error The Language you selected doesn't match Alexa Account Settings.

For the following source https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide.
I came to know that en-IN is also supported. Can you please let me know if we can change the language from en-EU to en-IN. 

Thanks
Kishore

**Comment by shivasiddharth** [comment]
Sorry, you are on the wrong git !

**Comment by akishoreplanon** [comment]
Hi Sid, Yes Is it was en-GB not en-EU it was a typo. Why can't we change the language to en-IN ?

**Comment by shivasiddharth** [comment]
I know that Alexa has been released in India, but for language selection, no such option exists.. If you want an answer for why it does not exist, you need to contact the Alexa guys.
