### ISSUE TITLE
Kodi integration 

### ISSUE THREAD

**Issue by antonistet** [shivasiddharth/GassistPi#82]
Hi, keep up the very nice work!   it would be very  cool if we could give voice commands to kodi like in kalliope voice project https://github.com/kalliope-project/kalliope. Is this something that you could add?

**Comment by antonistet** [comment]
update : https://github.com/OmerTu/GoogleHomeKodi#playlist-control
please check this

**Comment by shivasiddharth** [comment]
Thanks for the second link.  It looks more feasible, will take a look.

**Comment by shivasiddharth** [comment]
I have updated the project (Git) now with actions for controlling Kodi.  Ref: https://youtu.be/ahc6XKYriHo

**Comment by shivasiddharth** [comment]
Since, the kodi integration has been done, i am closing this issue. If you have any concerns, please feel free to reopen it..
