### ISSUE TITLE
how to setup custom wake word

### ISSUE THREAD

**Issue by kumarmohan7** [shivasiddharth/GassistPi#83]
how to setup custom wake word
i already download snowboy .pmdl file
how to add or setup my wake word GassistantPI
please help me.....

Thanks,
S.Mohankumar

**Comment by shivasiddharth** [comment]
place the downloaded model in the resources directory within the src folder, open the snowboy.py python file and scroll to a line that says models, in that change snowboy.umdl to snowboy.pmdl and save.
