### ISSUE TITLE
unable to fetch some archives

### ISSUE THREAD

**Issue by legemulo** [shivasiddharth/GassistPi#838]
This is the second day I have got this error. I have googled for a solution but nones that I have found fixed it. The system is updated and I have installed other packages before and after trying to install the assistant. It is a new install. I have also tried sudo apt-get clean. Thanks in advance.

Get:407 http://mirror.nbtelecom.com.br/raspberryPI/raspbian stretch/main armhf socat armhf 1.7.3.1-2+deb9u1 [320 kB]
Fetched 184 MB in 10min 8s (302 kB/s)
E: Failed to fetch http://archive.raspberrypi.org/debian/pool/main/m/mesa/libgl1-mesa-dri_13.0.6-1+rpi2_armhf.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:852f343bddad5ecb38d800eb3ef626f06e3e8c925411ec164ddc67051589729b
    - SHA1:2580274b86f9636147b6ed63d7a797c16d32f720 [weak]
    - MD5Sum:b3d38672dba0e36cf122ff6322715509 [weak]
    - Filesize:3899524 [weak]
   Hashes of received file:
    - SHA256:f2f329b8393716cf6f4198994f142f0a45de0dc074cabcfa532f94e30fa6eb59
    - SHA1:f135836092c3f5ce8d724760df720e28b791cb6c [weak]
    - MD5Sum:95133209c1af97c11bc1e3297ccd52e7 [weak]
    - Filesize:991232 [weak]
   Last modification reported: Mon, 25 Sep 2017 14:32:35 +0000
E: Failed to fetch http://mirror.nbtelecom.com.br/raspberryPI/raspbian/pool/main/libn/libnet-ssleay-perl/libnet-ssleay-perl_1.80-1_armhf.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:2804914fecaaa9b534b8ac09206db5915b467dd858fdc01c499bc8d78cdea34d
    - SHA1:cc50fb69528550ee401fcce44ac07ac6f7b676a4 [weak]
    - MD5Sum:84113e19b2097d58e5a16cbb0411b4ff [weak]
    - Filesize:269806 [weak]
   Hashes of received file:
    - SHA256:4ed3b4547f1caa1e58b1ec61684cd0c42e46c616cd3ab277df3b086dc12cea6c
    - SHA1:8de3f1a804a4e8854fb1e8009d000bd519072dcf [weak]
    - MD5Sum:5ff729dd4f5db87602eb773e3a5f5c17 [weak]
    - Filesize:2603 [weak]
   Last modification reported: Fri, 20 Jan 2017 10:08:10 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by shivasiddharth** [comment]
Meant to be posted in raspberry pi forums, not here.
