### ISSUE TITLE
When playing music from youtube I always get the same song

### ISSUE THREAD

**Issue by igiul667** [shivasiddharth/GassistPi#849]
Hi, I installed gassistpi yesterday, since google assistant on rpi couldn't play music on it's own. I have a problem when trying to play a song from youtube. It always plays the same song no matter what I say. I already checked [https://github.com/shivasiddharth/GassistPi/issues/753](url) and i tried 
pip install -r /home/pi/GassistPi/Requirements/GassistPi-pip-requirements.txt
as suggested in the post but I still get the same issue. Have a nice day

**Comment by aandroide** [comment]
surely you're wrong to say the command. the correct command is: ok google, play "song" from youtube

**Comment by igiul667** [comment]
I'm shure the command is right, I'm actually italian but it shoud be a supported language. Also should I open a new issue or keep using this?

**Comment by aandroide** [comment]
Se  nel file config.yaml hai impostato it-it,  il comando da dire in italiano è: riproduci bla bla bla da youtube

**Comment by igiul667** [comment]
Yes it is set to it-IT

**Comment by aandroide** [comment]
Hai anche inserito l'api key di youtube corretamente? Ed hai controllato che sia realmente attiva nella tua consolle di google?

**Comment by igiul667** [comment]
Ho appena finito di reinstallare ed ora va, grazie mille della disponibilità e buona giornata
