### ISSUE TITLE
Troubleshoot Google Assistant startup geting timed out

### ISSUE THREAD

**Issue by worldwidewoogie** [shivasiddharth/GassistPi#86]
Sometimes, due to a slow network, Google Assistant startup gets timed out. If you are having the same issue, please change the systemd file of gassistpi-ok-google.service as follows:

```
[Unit]
Description=Google Assistant
Wants=network-online.target
After=network-online.target

[Service]
Environment=VIRTUAL_ENV=/home/pi/env
Environment=PATH=/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py
WorkingDirectory=/home/pi/
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target

```

**Comment by shivasiddharth** [comment]
Thanks for the shout., i have modified your post and shall leave it open just in case.

**Comment by shivasiddharth** [comment]
I have updated the systemd files in the git. Closing this issue now. Thanks for your insight.
