### ISSUE TITLE
No such file or directory: "/home/pi/.config/google-oauthlib-tool/credentials.json"

### ISSUE THREAD

**Issue by ytz123** [shivasiddharth/GassistPi#87]
No such file or directory: "/home/pi/.config/google-oauthlib-tool/credentials.json" issue appers when trying to start google assistant

**Comment by shivasiddharth** [comment]
run this

`source env/bin/activate`

`google-oauthlib-tool --client-secrets /home/pi/assistant.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless
`
You will be asked to authenticate again after that it should be fine..

**Comment by ytz123** [comment]
never mind din't see the part were it said not to use Google AIY image sorry
