### ISSUE TITLE
Custom actions & functions to get transcript of user request 

### ISSUE THREAD

**Issue by vishalds2003** [shivasiddharth/GassistPi#899]
@shivasiddharth, you've got a great repository over here. So, as for this one, this is not an issue. 
I'm pretty new to GitHub as well as to the Google assistant library. And so, I don't know the correct ways to ask this doubt about this project. So, please do forgive me if I'm wrong and please do read on to address my _issue_.

I'm planning to do a small project using this code. But, I want to know some things about this code:
- Is there a function(natively in the Google Assistant Library or custom created by you) to **get the transcript of user request** given to the asisstant anywhere in this project?
- In the same way, is there a function to get a **text transcript of responses** provided by the assistant?
- How does one **write functions for adding custom actions** into this already existing project?

I went through the whole code. But, according to what I've seen, there are no such functions to be found. Also, I think that most of the features described in the README.md are defined as functions in the **/src/actions.py**. But, in that, I haven't seen a **main()** function which calls all the functions. It mainly just has all the function definitions. So, where are all these functions called in the code? Can you please explain? It's really important..

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi#do-not-raise-an-issue-request-for-non-issue-stuff-for-non-
