### ISSUE TITLE
How to change trigger word for GPIO controls

### ISSUE THREAD

**Issue by vishalds2003** [shivasiddharth/GassistPi#901]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Board:
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 2
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: BCM2835
Revision	: a21041
Serial		: 00000000df98f327

OS:
 PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Describe the bug:
```
It is mentioned in the README.md that the trigger word for controlling the GPIO's can be changed in the main.py code. But, I'm unable to find the word in the code. Can you please specify in which line is that present..?
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

### If answer to question 2 is Yes, then paste the contents of the terminal below.

```
Answer is no
```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```
Answer is NO
```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

### Attach the log file named Gassistpi.log
Log file can be found in /tmp/ directory

**Comment by shivasiddharth** [comment]
I have already emphasized on this a number of times: https://github.com/shivasiddharth/GassistPi#do-not-raise-an-issue-request-for-non-issue-stuff-for-non-issue-help-and-interaction-use-gitter-

**Comment by vishalds2003** [comment]
Well, I'm sorry. But there was no word in the main.py which seems like the one you mentioned..

**Comment by vishalds2003** [comment]
What is just there in the whole code is:
Line 571 : `def interpreter_mode_trigger(self,switch):`
Line 610 : `self.interpreter_mode_trigger('Stop')`
Line 918 : `self.interpreter_mode_trigger('Start')`
Line 920 : `self.interpreter_mode_trigger('Stop')`
So, where should I change the trigger word? None of these specifies a trigger word anywhere.. Where should I change?

**Comment by shivasiddharth** [comment]
Keywords need to be changed in the keywords file.  https://github.com/shivasiddharth/GassistPi/blob/e8d65ecd690b89e73f483326aa47f43259a4bec0/src/keywords_en.yaml#L16
