### ISSUE TITLE
PushBullet SMS

### ISSUE THREAD

**Issue by xPandasheepx** [shivasiddharth/GassistPi#927]
Hi, I would like to know it there would be a way to use the sms part of push bullet instead of always just texting to myself.
Any help would be appreciated,
Thanks in advanced!

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi#do-not-raise-an-issue-request-for-non-issue-stuff-for-non-issue-help-and-interaction-use-gitter-   ??
