### ISSUE TITLE
Sugestion: Push Bullet SMS

### ISSUE THREAD

**Issue by xPandasheepx** [shivasiddharth/GassistPi#928]
hello,
I have been testing out different ways I can change things in the config.yaml or actions.py files to make it so that PushBullet can not only send messages to myself, but to others with it's sms feature. I think this would be very helpful, and if any one could reply with an answer that would be helpful.

**Comment by shivasiddharth** [comment]
I specifically pointed out in the last issue that you opened to this part on the README https://github.com/shivasiddharth/GassistPi#do-not-raise-an-issue-request-for-non-issue-stuff-for-non-issue-help-and-interaction-use-gitter-
