### ISSUE TITLE
service-installer.sh not running

### ISSUE THREAD

**Issue by pallaprasannakumar02** [shivasiddharth/GassistPi#93]
service-installer.sh is not running

Followed entire process but nothing is running on startup

**Comment by shivasiddharth** [comment]
After executing the service installer, you should enable the services. What do you mean like nothing is running on startup ? You dont even hear the "welcome audio"?

**Comment by pallaprasannakumar02** [comment]
yeah,  i have did the same thing and rebooted, i didnt heard welcome audio

**Comment by shivasiddharth** [comment]
Did you see this. #86 ?

**Comment by shivasiddharth** [comment]
Since, nothing was communicated after, the issue is deemed resolved. Closing this !
