### ISSUE TITLE
re-installer stops installing swig showing sudo: ./autogen.sh: command not found and stops

### ISSUE THREAD

**Issue by bishnutosh** [shivasiddharth/GassistPi#951]
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Paste your Board and OS details here.   
pi@orangepipc:~$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : Allwinner sun8i Family
Revision        : 0000
Serial          : 02c001818bce5493
`pi@orangepipc:~$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 22.85
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : Allwinner sun8i Family
Revision        : 0000
Serial          : 02c001818bce5493
pi@orangepipc:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
``

### Describe the bug:
`everytime i try to install goog
le assistant with the one line installer, it stops at installing swig and halts the process showing sudo: ./autogen.sh: command not found``

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No
yes
### 2. Is the issue related to assistant installation ?
Yes/No
yes
### If answer to question 2 is Yes, then paste the contents of the terminal below.
pi@orangepipc:~$ cd /home/${USER}/
pi@orangepipc:~$ sudo chmod +x ./GassistPi/scripts/gassist-installer.sh
[sudo] password for pi:
pi@orangepipc:~$ sudo  ./GassistPi/scripts/gassist-installer.sh

Enter the your full credential file name including the path and .json extension: /home/pi/client_secret_546308721749-830okuv1q4f8vhh3roavvc0ttcekvg67.apps.googleusercontent.com.json

Enter the your Google Cloud Console Project-Id: orange-pi-assistant-e0345

Enter the modelid that was generated in the actions console: orange-pi-assistant-e0345-orange-pi-pc-z12q2i

Hit:1 http://ports.ubuntu.com bionic InRelease
Get:3 http://ports.ubuntu.com bionic-security InRelease [88.7 kB]
Get:4 http://ports.ubuntu.com bionic-updates InRelease [88.7 kB]
Get:5 http://ports.ubuntu.com bionic-backports InRelease [74.6 kB]
Hit:2 https://apt.armbian.com bionic InRelease
Get:6 http://ports.ubuntu.com bionic-updates/main armhf Packages [518 kB]
Get:7 http://ports.ubuntu.com bionic-updates/multiverse armhf Packages [3596 B]
Fetched 774 kB in 4s (176 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
bison is already the newest version (2:3.0.4.dfsg-1build1).
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libjack-jackd2-dev is already the newest version (1.9.12~dfsg-2).
libmpg123-dev is already the newest version (1.25.10-1).
libpcre3 is already the newest version (2:8.39-9).
libpcre3-dev is already the newest version (2:8.39-9).
nmap is already the newest version (7.60-1ubuntu5).
python is already the newest version (2.7.15~rc1-1).
python-dev is already the newest version (2.7.15~rc1-1).
python-setuptools is already the newest version (39.0.1-2).
python3-setuptools is already the newest version (39.0.1-2).
socat is already the newest version (1.7.3.2-2ubuntu2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
libatlas-base-dev is already the newest version (3.10.3-5).
mpg123 is already the newest version (1.25.10-1).
mplayer is already the newest version (2:1.3.0-7build2).
mpv is already the newest version (0.27.2-1ubuntu1).
portaudio19-dev is already the newest version (19.6.0-1).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
git is already the newest version (1:2.17.1-1ubuntu0.4).
libxml2-dev is already the newest version (2.9.4+dfsg1-6.1ubuntu1.2).
libxslt1-dev is already the newest version (1.1.29-5ubuntu0.1).
python3-lxml is already the newest version (4.2.1-1ubuntu0.1).
libsox-fmt-mp3 is already the newest version (14.4.2-3ubuntu0.18.04.1).
sox is already the newest version (14.4.2-3ubuntu0.18.04.1).
vlc is already the newest version (3.0.7.1-0ubuntu18.04.1).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.4).
python3 is already the newest version (3.6.7-1~18.04).
python3-dev is already the newest version (3.6.7-1~18.04).
python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
python3-venv is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
The directory '/home/pi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyaudio in /usr/local/lib/python2.7/dist-packages

===========================Checking OS Compatability=========================

===========You are running the installer on Bionic==========

===========Your board supports Ok-Google Hotword. You can also trigger the assistant using custom-wakeword==========

===========GPIO pins cannot be used by default with the assistant. You need to figure it out by yourselves==========

==========Snowboy wrappers provied with the project are for Raspberry Pi boards running Raspbian Stretch. Custom snowboy wrappers need to be compiled for your setup==========

==========Installing Swig=========

sudo: ./autogen.sh: command not found
pi@orangepipc:~$
```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

### Attach the log file named Gassistpi.log
Log file can be found in /tmp/ directory

**Comment by bishnutosh** [comment]
why the installer shows sudo: ./autogen.sh: command not found .is there any way to solve it.i have already tried to install automake autoconf still not solved

**Comment by shivasiddharth** [comment]
For orangepi  boards i suggest using Armbian Stretch on kernel 4.14.

**Comment by bishnutosh** [comment]
thanks for response,i will try it.

**Comment by bishnutosh** [comment]
it worked man.thanks
