### ISSUE TITLE
Error in streaming Youtube

### ISSUE THREAD

**Issue by littlerockplanet** [shivasiddharth/GassistPi#96]
I get this error whenever I try to stream any Youtube, is there a way to fix it and is this a common problem?
It was working yesterday however it stopped working a few hours ago.

![image](https://user-images.githubusercontent.com/16112883/34241983-35496c32-e66d-11e7-8f27-a762a7eb02b9.png)

**Comment by littlerockplanet** [comment]
I figured this out by changing line 143:
playshell.stdin.write(bytes("...", "utf-8") is now  playshell.stdin.write(bytes(("...").encode( "utf-8")))

**Comment by shivasiddharth** [comment]
Glad that, you figured out the issue. CLosing this ..
