### ISSUE TITLE
kodi GassistPy

### ISSUE THREAD

**Issue by Enzoinventor** [shivasiddharth/GassistPi#99]
hello,how do i enable kodi on the raspberry? do I have to install it first?I did not understand how to enable port 8080 etc.

**Comment by shivasiddharth** [comment]
You can find all the details in the readme and for more clarity here is a video. https://youtu.be/ahc6XKYriHo

**Comment by Enzoinventor** [comment]
sorry but you can not use kodi on the same raspberry where is installed assistant? do you need to use a second raspberry?

**Comment by shivasiddharth** [comment]
You can. You nee to change the ip to localhost. Thats it.
